### ISSUE TITLE
[question] Possibility to change the device of a stream ?

### ISSUE THREAD

**Issue by Salamandar** [andrewrk/libsoundio#102]
When a device configuration changes (number of channels, mostly), I get an event but the output device does not change. How should my code behave ? Close the stream and device, open the new device then a new stream ?
Thanks a lot ;)

**Comment by andrewrk** [comment]
The way you are intended to do that is indeed destroying the stream and creating a new one with the new device.

**Comment by Salamandar** [comment]
Okay, thanks :)
