### ISSUE TITLE
C99 compatibility

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#111]
In the interests of greater compatibility, accommodation of long upgrade cycles, and wider adoption of libsoundio in general, I would like the library to be compatible with a C99 build environment.

This means addressing `src/atomics.h`.

I reviewed issue #48, and I believe the proposal there was not the right approach. It brought in a whole implementation of `stdatomic.h` adapted from FreeBSD, and not only would have imposed a new maintenance burden on libsoundio, it required either Clang, GCC 4.7+, or some non-standard compiler builtins. And at any rate, it was overkill for what was needed: a C99-friendly implementation of the `SOUNDIO_ATOMIC_*` macros, no more and no less.

[Here I submit a patch](https://github.com/andrewrk/libsoundio/files/512227/libsoundio-c99-atomics.patch.txt) with a first-draft cut of these macros built on POSIX-thread mutexes. This kinda-sorta works on Linux as-is, but there are three issues I'd like to address that will require changes elsewhere:

1. This should use `SoundIoOsMutex` instead of `pthread_mutex_t`, so that it can work outside of POSIX. But that brings us to...

2. These atomic types need initialization. Straight `pthread_mutex_t` allows static initialization, and at least on Linux, `PTHREAD_MUTEX_INITIALIZER` is all zeroes, so starting with zeroed-out memory is enough. But that's not always going to be the case, and of course a `SoundIoOsMutex` needs to come from `soundio_os_mutex_create()`.

 The initialization, and destruction, can be wrapped up in new macros consistent with the existing ones. Something like
 ```
     SOUNDIO_ATOMIC_INIT(rb->write_offset, 0);
     /* ... */
     SOUNDIO_ATOMIC_DESTROY(rb->write_offset);
 ```
3. This implementation makes use of GCC-specific statement expressions, as well as `typeof()`. I found this to be a necessary evil to reproduce the type-agnostic nature of the macros (i.e. the same macro works with a `long`, `int`, `bool` or `flag`).

 I'd like to suggest redrawing these macros to include the type (so e.g. `SOUNDIO_ATOMIC_LOAD()` becomes `SOUNDIO_ATOMIC_INT_LOAD()`, `SOUNDIO_ATOMIC_BOOL_LOAD()` and so on). This would allow implementing the macros using [static inline] functions, with which compiler compatibility will no longer be an issue.

 (A possible alternative approach is to do an OO-in-C thing, placing function pointers with appropriate argument/return types inside the atomic-type structs, and then the macros expand to a call to the appropriate function pointer. That should allow the macros to remain type-agnostic. But I'd prefer the simpler approach enabled by going with type-specific macros.)

In addition to all that, I put in some better feature-test logic, since this kind of thing really needs it. (The C++ case would need an external check for the `<atomic>` header, so it is left commented out for now.) Better to give a clear `#error` instead of a confusing syntax error.

**Comment by fsateler** [comment]
@iskunk why not provide a proper PR instead of attaching patches? it makes taking a look less convenient.

**Comment by iskunk** [comment]
I don't have a proper setup for such Git-fu at present, I'm afraid. And in any event, this isn't nearly ready to go in yet.

Patches are easy, once you get around the `-p` option ^_^

**Comment by andrewrk** [comment]
This patch is not a workable solution to supporting C99 because we rely on atomics being lock-free.

**Comment by andrewrk** [comment]
Also, to be clear, libsoundio headers are C99 compatible. Only the implementation requires C11. What system and/or platform are you having trouble finding a C11-compatible compiler?

**Comment by iskunk** [comment]
@andrewrk, can you elaborate on the requirement for lock-free atomics? My understanding is that lock-free yields better performance, but mutexes are otherwise logically equivalent.

Red Hat Enterprise Linux 6, with GCC 4.4, is due to be supported till at least 2020. I understand that embedded-system toolchains often stay behind the curve as well, though I have much less experience there.

(Sure, you may be able to find some unofficial package of a newer GCC and install that, or even build GCC yourself. But that then becomes a fairly major dependency for libsoundio, one not shared by many of its competitors.)

**Comment by andrewrk** [comment]
You are correct that lock free yields better performance but mutexes are otherwise logically equivalent. However the problem is that real time performance demands a deterministic upper bound on latency and mutex locks do not guarantee a upper bound on latency within requirements.

In other words, if, in the audio callback, one locks a mutex, there is no guarantee that this lock operation will return within enough time to fill the audio buffer so that no glitches happen. There is some latency for the audio buffer, say for example 15ms, and a mutex lock is not guaranteed to return within this time. It is not acceptable for such an audio glitch to happen during a performance or any professional use of libsoundio.

**Comment by fsateler** [comment]
They are not logically equivalent as deadlocks are possible with mutexes
but not possible with lock-free structures.

**Comment by iskunk** [comment]
> However the problem is that real time performance demands a deterministic upper bound on latency and mutex locks do not guarantee a upper bound on latency within requirements.

Okay, a few things:

* Real-time/professional performance is a good use case, of course, and I'm glad that you're addressing it. (LibAO would never have passed muster here.) But is libsoundio targeting that exclusively? Applications like, say, an ordinary music player will typically fill up a larger buffer, accepting greater latency and rendering real-time concerns moot. And being able to build in an older environment a libsoundio that is good enough, rather than having to bring in a whole new toolchain for reasons that have nothing to do with more modest use cases, will be appreciated by many users.

 (There would certainly be nothing wrong with a recommendation to build the library using a C11 compiler and bona-fide atomics if the user has performance-critical needs. Heck, they may want to optimize for their CPU while they're at it. All low-hanging fruit for a pro.)

* What kind of contention are you foreseeing for these atomic types? You have a playback/capture thread, and then one [or maybe a handful of] application threads that interact with libsoundio. The mutex is held for an extremely short time, literally just doing a fetch/store/add/swap and then releasing. You would have to have some pretty extreme contention for that to amount to more than e.g. 0.1 ms on any recent CPU.

 (Mutex latency usually becomes an issue when you're doing something in the critical section that takes a lot of time, like heavy computation or disk I/O. And that could arguably be called poor programming practice.)

* Yes, mutexes don't give a hard guarantee on latency---but if that's a concern, I would think that the use of a non-real-time kernel would be a _much_ bigger deal. Again, a performance-oriented user may go with the custom-tuned kernel, or even a stripped-down OS. Focusing on mutex latency around a minuscule critical section (and in a compatibility-fallback case at that) seems like going for the pennies rather than the pounds.

> They are not logically equivalent as deadlocks are possible with mutexes
but not possible with lock-free structures.

True, but "possible with mutexes" really means "possible if you use mutexes carelessly." You're not going to get a deadlock when a resource is protected by a single mutex. Multiple threads hitting that resource will get serialized access; there's literally no way for a deadlock to occur.

Now, if you bring signal handlers into the picture (and the handler tries to access the resource), then that's [a whole 'nuther can of worms](http://www.linuxquestions.org/questions/programming-9/locking-mutex-in-a-signal-handler-function-789218/). But libsoundio doesn't use POSIX signals (and would lose non-POSIX compatibility if it did), so that's not an issue.

**Comment by fsateler** [comment]
>> They are not logically equivalent as deadlocks are possible with mutexes but not possible with lock-free structures.
>
>True, but "possible with mutexes" really means "possible if you use mutexes carelessly."

Famous last words ? 😉 

Anyway, if redhat with gcc 4.4 is your concern, I think you can instead use the [gcc atomic builtins](https://gcc.gnu.org/onlinedocs/gcc-4.4.0/gcc/Atomic-Builtins.html)

**Comment by iskunk** [comment]
> Famous last words ?

If you're handling a gun, be sure that you're not pointing it at your feet ;-)

> Anyway, if redhat with gcc 4.4 is your concern, I think you can instead use the gcc atomic builtins

Yes, I saw those. That's another way to go, but of course it only covers GCC 4.4+; you'd still need another fallback for compilers without those builtins. Because these compatibility fallback(s) are already going to be less used than the C11/C++ paths, IMO it's better for testing/coverage purposes to have just one fallback instead of two---even if it means forgoing available atomic builtins.

**Comment by andrewrk** [comment]
> you'd still need another fallback for compilers without those builtins.

Let's focus on actual use cases. libsoundio supports the official C11 standard, which, ideally, should be good enough for everyone. But pragmatically, some systems are stuck with older compiler versions, and it makes sense to support those older versions... for now.

But let's not imagine extra use cases to give more work to ourselves unnecessarily.

Redhat with gcc 4.4 is a reasonable use case. Any other platforms with users you need to support, that are somehow unable to upgrade their C compiler to a standard that came out 5 years ago?

**Comment by iskunk** [comment]
> But let's not imagine extra use cases to give more work to ourselves unnecessarily.

All _we_ would do is add one catch-all fallback case. (I'm assuming that you would agree in not wanting the "more work" of the additional GCC-atomic fallback.)

> Any other platforms with users you need to support, that are somehow unable to upgrade their C compiler to a standard that came out 5 years ago?

It's less a matter of enumerating platforms that you want to support, and more about keeping options open for users and systems that you may not have foreseen. That's part of the reason to offer up the source code in the first place.

And I should point out, just because a standard came out in year N doesn't mean that everyone's going to be on that standard in N+X years (where X is small). C99 may have technically come out in 1999, but if I recall correctly, it wasn't till at least a decade later that major GNU projects started migrating to it. The installed base moves slowly.

Andrew, what's your concern here? I seriously doubt mutex latency is going to arise as a practical matter (I'm almost wondering if a difference can even be _measured_). I doubt that you're secretly pushing for C11 adoption by way of writing cool code that requires it. And the professional/performance use case is unlikely to be affected at all, because deadmau5 is not going to be running libsoundio on a 5-year-old system. So what gives?

**Comment by pgiblock** [comment]
Actually, "mutex latency" is the entire issue. If the code must be realtime-safe (which is required by the Jack callback, at least) then one must not rely on Mutexes. This is kind of the point of a library such as libsoundio, is it not? Let this one library deal with the difficult parts so the developer doesn't need to.

That said, unfortunately, I believe there are two approaches to take as a fallback to C11. One is to use compiler-specific constructs (like GCC's atomics). The other is to rely on platform-specific constructs (like dropping into x86 assembly).

I do believe that it is a worthwhile effort and should be integrated should someone develop a sufficient patch. This is an "actual use case", but I understand the core developers not wanting to focus on this until such a need is apparent.

**Comment by iskunk** [comment]
>  If the code must be realtime-safe (which is required by the Jack callback, at least) then one must not rely on Mutexes. This is kind of the point of a library such as libsoundio, is it not?

My understanding is that real-time is _a_ use case of libsoundio, but not the only one. You could use libsoundio as the backend for a WinAmp-like music player, for example, which won't have anywhere near the same kind of latency requirements. (For my part, I'm looking to use libsoundio as a replacement for the unmaintained LibAO, a library whose personification says "Latency? Whuzzat?")

And remember, this is not about changing libsoundio to always use mutexes instead of atomic types. This is about making it possible to build a libsoundio that uses mutexes when atomic types are not available. If you're running the latest Ubuntu, then nothing changes for you.

> That said, unfortunately, I believe there are two approaches to take as a fallback to C11. One is to use compiler-specific constructs (like GCC's atomics). The other is to rely on platform-specific constructs (like dropping into x86 assembly).

Neither of these is a catch-all, nor in my view even desirable (from a maintainability standpoint).

Real-time is not always going to be needed. In fact, I fully expect that the majority of cases where libsoundio is used will _not_ require this, because there's a heck of a lot more music players than DAWs and laptop-EDM performers out there.

> This is an "actual use case", but I understand the core developers not wanting to focus on this until such a need is apparent.

I submitted this because _I_ have such a need. And if libsoundio becomes as popular as the polished Web site seems to anticipate, I won't be the only one.

**Comment by andrewrk** [comment]
I'm personally not going to work toward the goal of being able to compile with C99. Let the world catch up to C11. To re-iterate in case anyone arrives here from a search engine, libsoundio headers are C99 compatible; the question is about being able to compile the libsoundio implementation with C99.

In the meantime, anyone who wants to be able to compile libsoundio with C99 is free to submit a pull request that accomplishes this goal without compromising the realtime performance of the codebase, and I would merge and maintain such a pull request.
