### ISSUE TITLE
Improve ring buffer documentation

### ISSUE THREAD

**Issue by Yepoleb** [andrewrk/libsoundio#113]
I was very confused because the soundio ring buffer doesn't have code to deal with wrap-around. Only after coming across this [HN post](https://news.ycombinator.com/item?id=11122580) it started to make sense. It's a very nice concept, but it needs a good explanation of what's going on. Also the SoundIoRingBuffer struct is missing a Doxygen entry.

**Comment by iskunk** [comment]
I second this. Not only the ring buffer, but also `SoundIoOsMirroredMemory`. The code in `soundio_os_init_mirrored_memory()` left me scratching my head until I (independently) came across that same HN post.

It's a clever hack, to be sure---but it's precisely the clever stuff that most needs comments/documentation.

**Comment by andrewrk** [comment]
`SoundIoOsMirroredMemory` is not exposed in the public API. I'll see if I can touch up the docs for ring buffer though.

**Comment by andrewrk** [comment]
Looks like Doxygen isn't smart enough to pick up on this documentation.

```
/// A ring buffer is a single-reader single-writer lock-free fixed-size queue.
/// libsoundio ring buffers use memory mapping techniques to enable a
/// contiguous buffer when reading or writing across the boundary of the ring
/// buffer's capacity.
struct SoundIoRingBuffer;
```

I'll move it to `soundio_ring_buffer_create`.
