### ISSUE TITLE
Can't access userdata from callback

### ISSUE THREAD

**Issue by Yepoleb** [andrewrk/libsoundio#114]
The callbacks `emit_rtprio_warning`, `jack_info_callback` and `jack_error_callback` don't receive a pointer to the SoundIo instance and therefore don't have access to the userdata. Working around this limitation seems to be impossible without using globals or ugly hacks. I know changing the API is a big deal, so I'd be interested in alternative solutions.

**Comment by andrewrk** [comment]
Wow, I made a mistake there. I think we'e due for a 2.0.0 release really soon anyway because of some other needed changes. Let's just fix the API and then bump the major version.

**Comment by Yepoleb** [comment]
How soon? I've found a few inconsistencies I'd like to suggest changing before the API gets frozen.

**Comment by andrewrk** [comment]
I've got a session scheduled for tomorrow to get a bunch of libsoundio issues resolved and push out a bug fix release as well as a major version release.

**Comment by Yepoleb** [comment]
There are a lot of changes. I think it's better to only do a pre-release and wait for some feedback before doing a stable one, unless there will still be adjustments possible after 2.0.0. I'd definitely take a look and @iskunk might as well.

**Comment by Yepoleb** [comment]
There are a lot of changes. I think it's better to only do a pre-release and wait for some feedback before doing a stable one, unless there will still be adjustments possible after 2.0.0. I'd definitely take a look and @iskunk might as well.

**Comment by andrewrk** [comment]
I can fix this for `emit_rtprio_warning` but not for the jack functions. See above for a link to the Jack issue I just filed.

**Comment by andrewrk** [comment]
Oops didn't mean to close yet.

**Comment by andrewrk** [comment]
Fixed in v2 branch.

**Comment by andrewrk** [comment]
@Yepoleb I didn't quite make it through all the issues I wanted to today, but made some substantial progress. I'll schedule some more time next weekend too.
