### ISSUE TITLE
Inconsistent enum to string function names

### ISSUE THREAD

**Issue by Yepoleb** [andrewrk/libsoundio#115]
There doesn't seem to be any pattern in the way these functions are named:

* `soundio_strerror` - converts `SoundIoError`
* `soundio_format_string` - converts `SoundIoFormat`
* `soundio_backend_name` - converts `SoundIoBackend`
* `soundio_get_channel_name` - converts `SoundIoChannelId`

I also noticed that only some of the enums have an `Id` suffix. It could be a good way to differentiate them from structs.

**Comment by andrewrk** [comment]
fixed in v2 branch
