### ISSUE TITLE
Offer simple push-play API

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#119]
Libsoundio is built around a "pull" model for obtaining sound data from the application. This means that a user-provided callback function fires whenever more samples are needed. This is a sound design for high-performance, low-latency use cases.

But for many less-advanced applications, the pull model amounts to needless complexity. Say you have a simple console-based MP3 player program like `mpg123`. All you're doing is iterating over MP3 frames, decoding them, writing them to the audio device, and (if you're being fancy) updating a playback status line on the terminal by printing `"...\r"` repeatedly. Your `audio_write()` function can (and is expected to) block, which is what keeps your status line synchronized to actual time. All you need to maintain glitch-free playback is for the function to return with enough lead time before an underrun.

I am working on an implementation of such a "push"-based interface for libsoundio. I would like to request comments on this proposed design:

```
int soundio_play(struct SoundIoOutStream *outstream, const char *frames, int frame_count);

int soundio_play_deadline(struct SoundIoOutStream *outstream, const char *frames, int frame_count, double *out_deadline);
```

(There is no corresponding `soundio_record()` set of functions in this proposal because recording is a less-common use case. It may be added later, but given that LibAO only handles playback, I believe there is not high demand for it.)

Both functions are called by the application, and take a buffer of interleaved frames.

`soundio_play_deadline()` returns as soon as all the frames have been read into libsoundio's buffer. The `*out_deadline` parameter returns the (future) timestamp at which an underrun will occur. The application can then use this information to plan how it will go about preparing the next batch of samples.

`soundio_play()` simply returns at a fixed amount of time (say, half a second) before the deadline. The amount of time is configurable via a (new) field in `struct SoundIoOutStream`. All this is really doing is calling `soundio_play_deadline()` and then sleeping for an appropriate amount of time, but this is a useful convenience for applications, especially if the sound buffer is large.

**Comment by andrewrk** [comment]
I suggest that such a high level API should exist in a different library.

Seems like it would make sense to implement mixing, resampling, decoding, into a library, which could depend on libsoundio. You might use this in a video game, for example when the player jumps, you could call `play_sound_effect(jump)` or some such. It would handle playing 2 sounds at once, decoding .ogg into raw samples, etc.

This is all stuff that seems like it belongs together, and not in libsoundio but in a higher level library that depends on libsoundio.

**Comment by iskunk** [comment]
I agree that mixing/resampling/decoding would belong in a separate library, because that is sound _processing_, not mere playback. But a blocking-play function is as valid an API interface for an audio I/O library as a callback framework. It's a different paradigm, and not as powerful a one, to be sure---but for certain classes of applications (and users), it's exactly what is needed. The libsoundio callback interface would be as inappropriate for them as a push-play function would be for the low-latency/real-time use cases you're focusing on.

(I'll also point out that PortAudio has [blocking I/O](http://portaudio.com/docs/v19-doxydocs/blocking_read_write.html), and LibAO only ever had [`ao_play()`](https://xiph.org/ao/doc/ao_play.html).)

**Comment by andrewrk** [comment]
> But a blocking-play function is as valid an API interface for an audio I/O library as a callback framework. It's a different paradigm, and not as powerful a one, to be sure---but for certain classes of applications (and users), it's exactly what is needed.

I agree with this 100%. However I believe that this API interface is one that can and should be built on top of the existing libsoundio interface.

I'm going to say no to this one, in the interest of keeping the scope limited and focused, and keeping this a project I can continue to maintain in my free time.
