### ISSUE TITLE
#include handling

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#120]
There are a handful of issues with how #include paths and headers are handled in libsoundio that I'd like to address here.
1. The order of the #include directories in the CMake build is incorrect. Currently, it is
   
   `$(backend_library_includes) -I$(srcdir) -I$(builddir) -I$(srcdir)/test -I$(srcdir)/src`
   
   First, the backend includes need to be at the end of the list, not the front. If some backend library ever happens to include a `soundio/soundio.h` header, the libsoundio build should ignore it and use its own.
   
   `-I$(builddir)` needs to go first, because headers in the build tree are supposed to override headers in the source tree. (E.g. if `config.h` is in both locations, the build-tree copy is the one that should be used.)
   
   I would also note that there need to be corresponding build-tree equivalents of the last two directives. However, both can be dropped, because (A) there are no header files in the "test" subdirectory, and (B) all the headers in "src" are pulled in via `#include"..."`, which already looks in the current directory.
2. `src/config.h.in` should be moved to the top-level directory, as that is the location where it is instantiated.
3. `config.h` needs to be #included as the very first header in each C module. The config header is considered to be equivalent to `-DFOO` directives on the compiler command line, so one could put feature-test macros (e.g. `_POSIX_C_SOURCE`) in there, and they should work. Feature-test macros need to be defined before any system header is touched, and the safest way to do this is to have the explicit #include at the top of every file.
   
   Optionally, the `config.h` #include can be surrounded by `#ifdef HAVE_CONFIG_H` (and then `add_definitions(-DHAVE_CONFIG_H)` added to the CMake listfile). This allows the source to be built in two modalities: definitions on the compiler comand line, or in a config header. If alternate build systems come about for libsoundio (e.g. an NMAKE makefile for Windows users), then this will be helpful.
4. `config.h` should be #included with `#include<...>` rather than `#include"..."`. This addresses the case of an out-of-source-tree build being done from a source tree in which an in-tree build was previously performed---in such a case, `#include"..."` may pull in the `config.h` file from the old in-tree build.
5. This is not required, but I would advise that in each source file, system headers and third-party library headers are included before any of libsoundio's. This is a pattern that, in the event of any conflicting definitions, will make the issue easier to diagnose---as the errors are more likely to arise in "our" code instead of "theirs."

I've made all these changes in my tree, and if everything looks good, I can provide a patch.

**Comment by andrewrk** [comment]
This generally sounds like reasonable stuff. Here's my proposal: I will close this issue, you open a pull request with your patch, and we'll take it from there. Sound good?
