### ISSUE TITLE
Fix detection of unsuitable JACK library

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#122]
Currently, when I build libsoundio on a Debian stable system with the JACK development libraries installed, it ends with this error:

```
[ 21%] Building C object CMakeFiles/backend_disconnect_recover.dir/test/backend_disconnect_recover.c.o
Linking C executable backend_disconnect_recover
libsoundio.so.1.1.0: undefined reference to `jack_set_port_rename_callback'
collect2: error: ld returned 1 exit status
CMakeFiles/backend_disconnect_recover.dir/build.make:88: recipe for target 'backend_disconnect_recover' failed
make[2]: *** [backend_disconnect_recover] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/backend_disconnect_recover.dir/all' failed
make[1]: *** [CMakeFiles/backend_disconnect_recover.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

When JACK is being detected in `cmake/FindJACK.cmake`, CMake needs to verify that the library contains `jack_set_port_rename_callback()`, or else report that JACK was not found.

This patch, against the v2 branch, fixes the issue:

[libsoundio-fix-jack.patch.txt](https://github.com/andrewrk/libsoundio/files/551602/libsoundio-fix-jack.patch.txt)

**Comment by ligfx** [comment]
Looks like this is related to #11 and #35.

**Comment by iskunk** [comment]
It's related all right, but no one ever actually fixed the thing :-]

**Comment by andrewrk** [comment]
Cool. Let's talk about this over in the pull request.
