### ISSUE TITLE
Fix rpath of installed binaries linked against dynamic libsoundio

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#126]
If you build libsoundio in a default configuration (dynamic + static libs), you can run the `sio_sine` example in the build directory and it works fine. You might then run `make install` to install everything.

But then, when you go to run the same example in its final installed location, you get this:

```
$ /tmp/libsoundio-install/bin/sio_sine
/tmp/libsoundio-install/bin/sio_sine: error while loading shared libraries: libsoundio.so.1: cannot open shared object file: No such file or directory
```

This patch fixes the issue: [libsoundio-fix-rpath.patch.txt](https://github.com/andrewrk/libsoundio/files/556934/libsoundio-fix-rpath.patch.txt)

**Comment by fsateler** [comment]
Please don't do this. RPATHs are evil when they point to a path in the ld search path.

https://wiki.debian.org/RpathIssue

**Comment by iskunk** [comment]
Not as evil as the error I quoted. From your link:

> Ideally, upstream should implement a build-system that supports turning RPATH usage off during configuration.

A build option is all you need.

**Comment by fsateler** [comment]
> A build option is all you need.

But your patch does not provide that. 

Here is a solution that does not do the rpath if the install dir is on the system search path from the [cmake wiki](https://cmake.org/Wiki/CMake_RPATH_handling#CMake_and_the_RPATH)

```cmake
# the RPATH to be used when installing, but only if it's not a system directory
LIST(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}" isSystemDir)
IF("${isSystemDir}" STREQUAL "-1")
   SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
ENDIF("${isSystemDir}" STREQUAL "-1")
```

**Comment by hotgloupi** [comment]
You might want to make your installation relocatable by just setting `RPATH=$ORIGIN/../lib`
Also, I would not use the automatic approach @fsateler suggested, just a standard cmake option like  
`cmake .. -DINSTALL_RPATH:BOOL=YES`

**Comment by andrewrk** [comment]
sounds like a problem with cmake, the operating system configuration, or packaging. We're not doing anything weird in the cmake config.

**Comment by iskunk** [comment]
> sounds like a problem with cmake, the operating system configuration, or packaging.

No sir. This is a problem with the libsoundio build system. As things stand, it installs broken binaries if you install a dynamic build to a non-system location.
