### ISSUE TITLE
Mark read-only struct fields with (conditional) const keyword

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#131]
Some struct fields in the libsoundio interface are marked as read-only. Like in `struct SoundIo`:

```
    /// Read-only. After calling ::soundio_connect or ::soundio_connect_backend,
    /// this field tells which backend is currently connected.
    enum SoundIoBackend current_backend;
```

I'd like to suggest a bit of preprocessor-fu to give teeth to this restriction:

```
#if defined(SOUNDIO_BUILDING_LIBRARY)
# define SOUNDIO_RO
#else
# define SOUNDIO_RO const
#endif

[...]

    /// Read-only. After calling ::soundio_connect or ::soundio_connect_backend,
    /// this field tells which backend is currently connected.
    SOUNDIO_RO enum SoundIoBackend current_backend;
```

**Comment by Yepoleb** [comment]
A const field is not just read-only, but also guaranteed to not change after initialization. Abusing the const specifier like this confuses other programmers and could lead to some really fun to debug optimization errors. We have getters and setters to enforce member access, not some dangerous preprocessor magic.

**Comment by iskunk** [comment]
From [CERT](https://www.securecoding.cert.org/confluence/display/c/EXP05-C.+Do+not+cast+away+a+const+qualification):

> **EXP05-C-EX3:** Because const means "read-only," and not "constant," it is sometimes useful to declare struct members as (pointer to) const objects to obtain diagnostics when the user tries to change them in some way other than via the functions that are specifically designed to maintain that data type. Within those functions, however, it may be necessary to strip off the const qualification to update those members.

I wouldn't mind getters and setters (and as a bonus, these would make the ABI more robust). But that is somewhat cumbersome in C, and I don't think there would be much interest in going that route.

**Comment by Yepoleb** [comment]
Cert.org offers independent community standards that are not part of the official ISO C standard. I can't find the exception you mention in the freely available [draft for C11](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) and it strongly contradicts the point that is made about casting away the const-qualifier:

> If an attempt is made to modify an object defined with a const-qualified type through use of an lvalue with non-const-qualified type, the behavior is undefined.

**Comment by iskunk** [comment]
That's the thing, however: The "object" of note is the struct, not the field. The struct is not const, so it can't be placed into read-only memory or the like.

The standard doesn't address this specific usage, but CERT suggesting it as a useful mechanism is a pretty strong endorsement.

**Comment by andrewrk** [comment]
The point of this would be to help developers. Adding this `SOUNDIO_RO` noise would cause more annoyance than it would help via use of `const`. As someone who has consumed a lot of C APIs I feel confident in this judgment call.

**Comment by iskunk** [comment]
> Adding this `SOUNDIO_RO` noise would cause more annoyance than it would help via use of `const`.

You mean like in struct assignments and such?

> As someone who has consumed a lot of C APIs I feel confident in this judgment call.

Fair enough.
