### ISSUE TITLE
Consistency of "current" field names in struct SoundIoDevice

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#132]
Some fields in `struct SoundIoDevice` are named `current_*` and others are named `*_current`. I think the latter designation should be favored, for consistency with other fields that place qualifiers like "count", "min" and "max" at the end of the name.

**Comment by andrewrk** [comment]
Not important enough to change. Let's focus on making the library more robust than haggling over unimportant names.

**Comment by iskunk** [comment]
> Not important enough to change.

This is a public interface. Once it's set in stone, there won't be room for regrets down the road.

**Comment by andrewrk** [comment]
The fields you're proposing to rename are not related in the way that having `_current` line up would imply, and therefore making this change, in addition to breaking everyone's code, would if anything cause more confusion.

**Comment by iskunk** [comment]
Re breakage: Targeting 2.0, there's going to be source breakage anyway. I wouldn't have proposed this if not for that.

What of `software_latency_current` and `sample_rate_current`? Should those have "current" as a prefix instead?

I see this as being in the same vein as the `_strerror()/_name()` issue. For sure, it's nitty-gritty stuff, but I appreciate that level of thought being put into an API.

**Comment by Yepoleb** [comment]
The enum to string function names were a much bigger mess than the word "current" being in the wrong location. A new major version isn't a incentive to change ever little detail about the API. It's still the same library and less unnecessary changes are always appreciated by other developers. Please just accept when an issue gets rejected as unimportant, you still have like 20 others that need attention.
