### ISSUE TITLE
ANSI C (C89) compatible library header

### ISSUE THREAD

**Issue by iskunk** [andrewrk/libsoundio#134]
Even though the implementation of libsoundio requires C11 (maybe C99) to compile, applications may wish to enforce an older C standard as a means of ensuring wider portability to less-current systems (along with keeping libsoundio as an optional dependency). C99 is becoming increasingly available, but many existing systems still top out at C89, and many projects have yet to find the new features of C99/C11 compelling enough to break compatibility with these.

Currently, the `soundio.h` header uses only two non-ANSI constructs: C++-style comments, and the `inline` keyword.

The `inline` keyword is not a big deal, because it is already common practice for applications to compile with something like `-Dinline=__inline__` (or even `-Dinline=`) when needed. So it is only the C++-comment syntax that would need to change to `/* ... */`.

(One other nit is that the enum lists have a comma after the last element, which produces warnings with GCC's `-pedantic`.)

The Doxygen documentation needs to remain unaffected, of course, so the C comments would take a form [equivalent](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html) to the existing ones.

If this looks good, I'll submit the converted header.

**Comment by Yepoleb** [comment]
What is the C++-comment syntax?

**Comment by iskunk** [comment]
Double-slashes. (As opposed to C-style slash-star, star-slash)

**Comment by andrewrk** [comment]
It also uses stdbool.h and stdint.h. May C89 rest in peace.

**Comment by iskunk** [comment]
> It also uses stdbool.h and stdint.h.

I should have titled this issue differently; what is really needed is actually a bit less stringent: the ability to compile cleanly with `-ansi -pedantic`. At least with glibc, those headers work fine in C89 mode.

> May C89 rest in peace.

You might be there already, but many others are not.
