### ISSUE TITLE
ring_buffer fails after several hours

### ISSUE THREAD

**Issue by Timmmm** [andrewrk/libsoundio#160]
So, I guess this is by design (surely you could have anticipated this), but the ring buffer uses a `long` for the read and write pointers that is only ever incremented. It never decreases.

Eventually it overflows and you get stack corruption (at least with the example code). For 48 kHz 2 channel LE16 audio on 32-bit systems this happens after approximately 3 hours (0x80000000 / 48000 / 2 / 2 seconds). As you can imagine, a stack smashing bug like this that only happens after 3 hours took me a while to track down! I'm a bit disappointed it has such an obviously-not-going-to-work cause.

You can do atomic modulus operations something like this:

```
void soundio_ring_buffer_advance_write_ptr(struct SoundIoRingBuffer *rb, int count) {
    SOUNDIO_ATOMIC_FETCH_ADD(rb->write_offset, count);
    do {
        long write_offset_wrapped = SOUNDIO_ATOMIC_LOAD(rb->write_offset) % rb->capacity;
    } while (!SOUNDIO_ATOMIC_COMPARE_EXCHANGE_WEAK(rb->write_offset, write_offset_wrapped));
}
```

Where `SOUNDIO_ATOMIC_COMPARE_EXCHANGE_WEAK()` is [`std::atomic::compare_exchange_weak()`](http://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange) and whatever the C equivalent is.

Here is a test you can do to check it works (compile as 32-bit).

	int capacity = 10000;
	
	SoundIo* soundio = soundio_create();
	SoundIoRingBuffer* ring_buffer = soundio_ring_buffer_create(soundio, capacity);
	
	for (int i = 0; i < 0x1000000; ++i)
	{
		char* write_ptr = soundio_ring_buffer_write_ptr(ring_buffer);
		memset(write_ptr, 0, 1000);
		soundio_ring_buffer_advance_write_ptr(ring_buffer, 1000);
		soundio_ring_buffer_advance_read_ptr(ring_buffer, 1000);
		if (i % 1000 == 0)
			printf("%d\n", i);
	}
	
	printf("Success\n");
	
	soundio_ring_buffer_destroy(ring_buffer);
	soundio_destroy(soundio);

**Comment by jacquesh** [comment]
Is it not reasonable to just switch to using unsigned integers for the read/write pointers in the ringbuffer?
I have little experience with std::atomic but I would expect that the behaviour matches that of normal integers (and I see no reason in the documentation to believe otherwise) and if that's the case then an unsigned integer does the correct thing: it overflows to 0 and carries on pointing to the expected index in the array.

**Comment by Timmmm** [comment]
Yeah actually I think that should work as long as the length of the ring buffer is a factor of 2^64.
