### ISSUE TITLE
Does endian.h belong to soundio?

### ISSUE THREAD

**Issue by Mark-Weston** [andrewrk/libsoundio#177]
In #27 you argued to delete ring buffer in v2.0 because it's 

> an independent concept from libsoundio

even though you said you

> agree that it's useful

I feel the same way about endian.h - while useful, it's an independent concept from libsoundio.

Perhaps host-machine endianness should be taken into account only by a binary I/O library, for performance reasons, though it's not really necessary - you can read/write data (even normalized IEEE754 floats/doubles) without any knowledge of host-machine endianness, albeit slower.

This is just a suggestion I've thought you'd like based on your reasoning to remove the ring buffer.

**Comment by andrewrk** [comment]
We depend on endian.h inside libsoundio's implementation.
