### ISSUE TITLE
Compile time error in JACK back end

### ISSUE THREAD

**Issue by Zistack** [andrewrk/libsoundio#18]
The error as printed by the compiler is thus:

    /home/zistack/Program_Files/libsoundio-1.0.0/src/jack.cpp: In function ‘int soundio_jack_init(SoundIoPrivate*)’:
    /home/zistack/Program_Files/libsoundio-1.0.0/src/jack.cpp:919:84: error: invalid conversion from ‘void (*)(jack_port_id_t, const char*, const char*, void*) {aka void (*)(unsigned int, const char*, const char*, void*)}’ to ‘JackPortRenameCallback {aka int (*)(unsigned int, const char*, const char*, void*)}’ [-fpermissive]
         if ((err = jack_set_port_rename_callback(sij->client, port_rename_calllback, si))) {
                                                                                        ^
    In file included from /home/zistack/Program_Files/libsoundio-1.0.0/src/jack.hpp:15:0,
                     from /home/zistack/Program_Files/libsoundio-1.0.0/src/jack.cpp:8:
    /usr/include/jack/jack.h:523:5: note:   initializing argument 2 of ‘int jack_set_port_rename_callback(jack_client_t*, JackPortRenameCallback, void*)’
     int jack_set_port_rename_callback (jack_client_t *client,
         ^

It would appear that you're trying to hand a void returning function into a place that expects an int returning function.

The compiler also complains about one of the flags passed to it.

    At global scope:
    cc1plus: error: unrecognized command line option ‘-Wno-c99-extensions’ [-Werror]

This may or may not be related.

I am running Arch Linux.  The first thing that I did when I saw this was sync my machine and try again, thinking that a header on the system could be wrong.  This did not work.  I'm not sure what other information you're going to need.  I am knowledgable about my system, so just ask.

**Comment by diogocp** [comment]
Looks like #7

**Comment by Zistack** [comment]
Apparently so.  Funny I didn't see it the first time around.  Unfortunately, it appears that the required version of Jack2 has not yet made it into Arch's repositories.  I'll work around this on my own then.
