### ISSUE TITLE
example code in readme.md causes access violation exception

### ISSUE THREAD

**Issue by ThatOneCheetah** [andrewrk/libsoundio#184]
As the title says.
The problem seems to lie within the following line: `float *ptr = (float*)(areas[channel].ptr + areas[channel].step * frame);`.
In particular `areas[channel].step` seems to be twice what it should be (8 instead of 4), making the pointer step *8 bytes* every time, even though the sample is provided as a 32-bit floating point (4 bytes). This is confirmed by changing `areas[channel].step` to `outstream->bytes_per_sample` (8 vs 4), as the example works fine that way.

 
Using the 64-bit pre-built binary, targeting Windows 10 Home N (64-bit), using WASAPI.

**Comment by ThatOneCheetah** [comment]
Issue was caused by usage of `char*` as opposed to `byte*`; changing all `char*` to `byte*` in my implementation fixed this issue. ( due to `sizeof( char ) == 2` whereas `sizeof( byte ) == 1` )

**Comment by kirbyfan64** [comment]
Wait, what platform is this? IIRC the standard says that `sizeof(char)` is always 1 byte; however, it *does* allow the size of a byte to be different from 8 bits.

**Comment by ThatOneCheetah** [comment]
I am invoking libsoundio from C#, perhaps there is a difference between the "C-definition" and the "C#-definition" of `char`
