### ISSUE TITLE
MacOS 10.9: non-default latency and non-current sample rate prevent sound output

### ISSUE THREAD

**Issue by WarrenWeckesser** [andrewrk/libsoundio#19]
I built libsoundio on a Macbook Pro (OS X 10.9.5).  The output of `sio_list_devices` is

```
$ ./sio_list_devices
--------Input Devices--------

Built-in Microphone (default)
  id: AppleHDAEngineInput:1B,0,1,0:1
  channel layouts:
    Stereo
  current layout: Stereo
  sample rates:
    44100 - 44100
  current sample rate: 44100
  formats: float 32-bit LE
  min software latency: 0.00031746 sec
  max software latency: 0.20897959 sec
  current software latency: 0.01160998 sec


--------Output Devices--------

Built-in Output (default)
  id: AppleHDAEngineOutput:1B,0,1,1:0
  channel layouts:
    Stereo
  current layout: Stereo
  sample rates:
    44100 - 44100
    48000 - 48000
    88200 - 88200
    96000 - 96000
  current sample rate: 44100
  formats: float 32-bit LE
  min software latency: 0.00031746 sec
  max software latency: 0.41795918 sec
  current software latency: 0.01160998 sec


2 devices found
```

When I run `sio_sine`, the program runs, but there is no sound generated.  Here's the output shown when I try the various keyboard commands:

```
$ ./sio_sine 
Backend: CoreAudio
Output device: Built-in Output
'p\n' - pause
'u\n' - unpause
'c\n' - clear buffer
'q\n' - quit
p
pausing result: (no error)
u
unpausing result: (no error)
c
clear buffer result: incompatible backend
q
```
I assume I have to configure something, but I don't know what it is.

**Comment by andrewrk** [comment]
> I assume I have to configure something, but I don't know what it is.

There shouldn't be any hidden configuration. This is difficult to troubleshoot as it is working fine on my OSX 10.10.4 laptop. I confess I have never tested libsoundio on an OS X version other than this. I wonder if that has anything to do with it.

Anyone else have access to a Macbook Pro 10.9.x who can see if this problem happens for them too?

**Comment by WarrenWeckesser** [comment]
FWIW: `write_callback()` is never called.

**Comment by andrewrk** [comment]
That's a helpful clue. It means that this function call...

```c
    if ((os_err = AudioUnitSetProperty(osca->instance, kAudioUnitProperty_SetRenderCallback,
        kAudioUnitScope_Input, OUTPUT_ELEMENT, &render_callback, sizeof(AURenderCallbackStruct))))
    {
        outstream_destroy_ca(si, os);
        return SoundIoErrorOpeningDevice;
    }
```

...whose purpose is to register the write callback, is not succeeding in registering a write callback, and also not returning an error code.

**Comment by davidgranstrom** [comment]
I just tried this (also running OS X 10.9.5), and found that changing the sample rate to any other value than 44.1 kHz makes the example work and I hear the sine as expected.

```
$ ./sio_list_devices

--------Input Devices--------

Built-in Microphone (default)
  id: AppleHDAEngineInput:1B,0,1,0:1
  channel layouts:
    Stereo
  current layout: Stereo
  sample rates:
    48000 - 48000
  current sample rate: 48000
  formats: float 32-bit LE
  min software latency: 0.00031250 sec
  max software latency: 0.19200000 sec
  current software latency: 0.01066667 sec


--------Output Devices--------

Built-in Output (default)
  id: AppleHDAEngineOutput:1B,0,1,1:0
  channel layouts:
    Stereo
  current layout: Stereo
  sample rates:
    44100 - 44100
    48000 - 48000
    88200 - 88200
    96000 - 96000
  current sample rate: 48000
  formats: float 32-bit LE
  min software latency: 0.00031250 sec
  max software latency: 0.38400000 sec
  current software latency: 0.01066667 sec
```

**Comment by WarrenWeckesser** [comment]
@davidgranstrom: I'll try it.   How do I change the sample rate?

**Comment by WarrenWeckesser** [comment]
@davidgranstrom: I was able to configure the sample rate using `Applications/Utilities/Audio MIDI Setup`.  By setting the output sample rate to 48000, I hear the sound.  Thanks for the tip!

**Comment by andrewrk** [comment]
Thanks for the clue, when I get back from travel I will see if I can reproduce the issue and then come up with a solution that does not involve having the user configure their computer to work.

**Comment by andrewrk** [comment]
On OSX 10.10.5 I cannot duplicate this issue. Regardless of what I set the sample rate to in Audio MIDI setup and regardless of what `--sample-rate` parameter I give to `./sio_sine` example, I hear the sound.

**Comment by andrewrk** [comment]
If either of you (eventually) update your OS to 10.10 or later I would be curious to see if you still have the issue. Meanwhile, there's not much I can do about this right now given that I don't have access to MacOS 10.9.x.

**Comment by tgoyne** [comment]
I poked at this a little on my machine that's still running 10.9. Something in CoreAudio endlessly logs "ERROR:     [com.apple.audio.IOThread.client] AUHAL.cpp:2470: AUIOProc: AUHAL::AUIOProc: mono buffer too small (557 > 512)" once the stream is started. 512 is the `buffer_frame_size` read in `refresh_devices()`, and 557 is the size calculated by multiplying the software latency by the target sample rate in `outstream_open_ca()`. Changing it to always use a buffer size of 512 makes it successfully output sound.

**Comment by andrewrk** [comment]
Boy it sure would be nice if they would give us that error as a code instead of logging it somewhere. It's no coincidence that one of the features of libsoundio is error codes for everything instead of logging to stdio.

Anyway, this is a great clue @tgoyne - thanks for finding that out. I'm going to dive back into that code and see if I can write a patch for you to try.

**Comment by andrewrk** [comment]
@tgoyne What about these values?

```
            rd.device->software_latency_min = avr.mMinimum / use_sample_rate;
            rd.device->software_latency_max = avr.mMaximum / use_sample_rate;
```

Is the 557 number within the range of avr.mMinimum and avr.mMaximum?

**Comment by tgoyne** [comment]
avr is {14,9216} for the device being used (other devices have similar ranges).

**Comment by andrewrk** [comment]
Can you try the macos9 branch I just pushed? That goes for other people who want to try this too.

Play with different sio_sine `--latency` and `--sample-rate` parameters. Note that not passing a latency parameter (leaving latency as default) is special and is also interesting to test.

Here's some of my results on 10.10. Sound works fine on all of them.

**Comment by andrewrk** [comment]
@tgoyne one more thing, I wonder if 10.9 is simply expecting power of two values. Can you try the old code, but hard code that 557 value to 1024 and see if it works?

**Comment by tgoyne** [comment]
Hardcoding 1024 doesn't work. The branch does work on default settings. I'll try it on a range of settings later today.

**Comment by andrewrk** [comment]
I suspect that if you use a sample rate other than the one specified in Audio/MIDI Setup along with a latency value that is not default, you will get the problem.

And it seems like a bug in CoreAudio, since the value we choose is within the minimum and maximum range.
