### ISSUE TITLE
WASAPI loopback support?

### ISSUE THREAD

**Issue by slole** [andrewrk/libsoundio#204]
Just a quick question: Does this library support loopback recording on windows? (more on this: https://docs.microsoft.com/en-us/windows/desktop/coreaudio/loopback-recording) I have some experience on the topic (I helped add this feature to: https://github.com/bastibe/SoundCard). If this feature is not supported I am ready to help add it. 

Thank you very much for any response in advance.

**Comment by open-trade** [comment]
> Just a quick question: Does this library support loopback recording on windows? (more on this: https://docs.microsoft.com/en-us/windows/desktop/coreaudio/loopback-recording) I have some experience on the topic (I helped add this feature to: https://github.com/bastibe/SoundCard). If this feature is not supported I am ready to help add it.
> 
> Thank you very much for any response in advance.

Have you added it?

**Comment by slole** [comment]
Yes! I actually ended up adding it myself. You can use it with the include_loopback flag when searching for "microphones".
