### ISSUE TITLE
Changelog for 2.0.0

### ISSUE THREAD

**Issue by chohner** [andrewrk/libsoundio#208]
Any chance of getting an update of  he [changelog](https://github.com/andrewrk/libsoundio/blob/master/CHANGELOG.md) regarding the new `2.0.0` release?

Seems like plenty of fixes were merged in but it is hard to go through the list of commits looking for the breaking change that triggered the major version update

**Comment by andrewrk** [comment]
the reason for the major version bump is 1 line:

https://github.com/andrewrk/libsoundio/compare/1.1.0...2.0.0#diff-d897ed132be11de5226ff2b131b5ea49R540

The API is backwards compatible but the ABI changed. So the soversion had to get bumped.

**Comment by chohner** [comment]
Thanks. Feel free to close and thanks for the great work

**Comment by davidebeatrici** [comment]
Shouldn't the `v2` branch be merged into `master` now that the version is bumped to 2.0.0?
