### ISSUE TITLE
Recording from an output device?

### ISSUE THREAD

**Issue by philippemnoel** [andrewrk/libsoundio#229]
Hello,

Is there a feature to record from an output device? I'm making an application which must record "what the user hears" when they use a device. I've tried selecting an output device (default speakers/headphones) and using an instream but that doesn't seem compatible.

Is it supported at all? If so how can I do it, if not what would you recommend doing?

Cheers,

Philippe

**Comment by Suhail** [comment]
I have the same question actually!

Here's some more info:
```
$ ./sio_record --device "AppleHDAEngineOutput:1F,3,0,1,1:0" out.raw
Invalid device id: AppleHDAEngineOutput:1F,3,0,1,1:0
```

from sio_list_devices:
```
--------Output Devices--------

Built-in Output
  id: AppleHDAEngineOutput:1F,3,0,1,1:0
  channel layouts:
    Stereo
  current layout: Stereo
  sample rates:
    44100 - 44100
    48000 - 48000
    96000 - 96000
  current sample rate: 48000
  formats: signed 16-bit LE, signed 32-bit LE, float 32-bit LE, float 64-bit LE
  min software latency: 0.00031250 sec
  max software latency: 0.08533333 sec
  current software latency: 0.01066667 sec
```

When I run sox: `sox -r 48000 -e floating-point -b 32 -c 1 out.raw out.wav` it's just silence.

**Comment by Suhail** [comment]
A mini update: I did manage to get this all working on Ubuntu 18.04 just fine.

**Comment by philippemnoel** [comment]
How did you fix the built-in output returning invalid?

**Comment by Suhail** [comment]
Unfortunately, I didnt. I wrote/read from dummy on Linux.

**Comment by philippemnoel** [comment]
Yeah that's what I ended up doing as well, maybe an interesting future feature?
