### ISSUE TITLE
how to handle write_callback API when creating language bindings

### ISSUE THREAD

**Issue by capr** [andrewrk/libsoundio#28]
I've noticed that the write callback is called from a different thread (using WASAPI on a Win7 x64 here). This makes it difficult to bind to dynamic languages (I was about to attempt a LuaJIT binding for instance). Is there anything that can be done about that, like, say a lock/write/unlock API like DirectSound?

How do you push data in the write callback if you can't even use locking primitives?

Thanks,
Cosmin.

**Comment by andrewrk** [comment]
The safest way to push data to the write callback is to use a ring buffer. libsoundio provides a ring buffer implementation ([docs](http://libsound.io/doc/soundio_8h.html#adcd0a77db4f04fbf5137abc7becda860)) for your convenience.

luajit is garbage collected, which means that it's generally not real-time safe. This means that the binding code you write in C will probably want to implement the write callback without exposing it directly in the API and do some internal buffering (via a ring buffer probably). Then you can have your lock/write/unlock API on top of that. At this point I would probably implement it without a callback style, but just allow the API user to push sound to or clear the ring buffer, and as long as it has enough sound buffered up you will get no underruns.

**Comment by capr** [comment]
Hi Andrew,

Thanks for answering. I have a few more questions.

In sio_record.c, I see that you use the ring buffer without locking. Does that mean that you can read from it in one thread and write to it in another thread safely without locking? That would solve the issue entirely.

[btw, I don't think garbage collection has anything to do with this, other than adding to the latency -- the problem I have is with the fact that the Lua interpreter state is not re-entrant so I can't enter into it from a callback called from another thread]

**Comment by andrewrk** [comment]
> In sio_record.c, I see that you use the ring buffer without locking. Does that mean that you can read from it in one thread and write to it in another thread safely without locking? That would solve the issue entirely.

Yes :-) The libsoundio ring buffer implementation is a fixed size, one reader, one writer, lock-free queue. It uses atomic integers for the read index and the write index.

> [btw, I don't think garbage collection has anything to do with this, other than adding to the latency -- the problem I have is with the fact that the Lua interpreter state is not re-entrant so I can't enter into it from a callback called from another thread]

I see - let me attempt to rename it again.

**Comment by capr** [comment]
Cool, thanks Andrew. I'll try the ring buffer idea then. Awesome work btw!

PS: I assume you don't care about WinXP (i.e. DirectSound) anymore right? :)

**Comment by andrewrk** [comment]
> PS: I assume you don't care about WinXP (i.e. DirectSound) anymore right? :)

Correct. Microsoft stopped supporting Windows XP on 2014-04-08, so I feel justified in not supporting it.

**Comment by andrewrk** [comment]
By the way, I am pleased to hear that you are writing luajit bindings to libsoundio. Feel free to ask me for a code review any time, and let me know when you release the first version and I will include a link to your project on http://libsound.io/.

**Comment by andrewrk** [comment]
I'm going to mark this as resolved - feel free to open another issue if you have further questions or concerns.
