### ISSUE TITLE
soundio_backend_count and soundio_get_backend should not require SoundIo * param

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/libsoundio#29]

**Comment by Yepoleb** [comment]
Looks like `soundio_ring_buffer_create` doesn't need a `SoundIo*` param either to me.

**Comment by andrewrk** [comment]
That one does because it depends on having called `soundio_create` at some point to initialize the OS layer code. Instead of documenting this dependency, I added it as a parameter to ensure that it will have happened. Seems less error prone.

**Comment by Yepoleb** [comment]
I think an assertion is a better way to solve this problem. Unless the user has a race condition in his code, the order in which the objects get initialized will always be the same. That makes it very likely to see the assertion fail on the first try.

If you want to keep the parameter, you should add a note saying a null pointer works too, as long as `soundio_create` has been called before. Carrying a useless pointer around can sometimes make things more complicated, just to prevent irresponsible programmers from making a simple mistake.

**Comment by andrewrk** [comment]
I hear what you're saying but in order to perform this assertion, we would have to lock a mutex, do the assertion, and then unlock a mutex.

In practice, is this parameter causing an issue?

I can add that note to the docs.

**Comment by Yepoleb** [comment]
It's not a serious issue, just an inconvenience and an ugly implementation, that shouldn't be in a polished product. Do you need the mutex for accessing a boolean or is there a more complicated process going on? How much delay would it introduce compared to the os calls that follow?

**Comment by andrewrk** [comment]
I think it's pretty convenient and elegant to prevent the user from having a bug without even requiring them to read the docs simply by adding a dependency on a struct they necessarily will have created.

It's a reasonable dependency. `SoundIo *` is essentially the global state that libsoundio functions need. It would even have been reasonable for the OS layer code to put the information in a `SoundIo` struct rather than globals protected by mutexes.

You can see why the mutex is necessary in the implementation of `soundio_os_init`.

**Comment by andrewrk** [comment]
This issue is fixed in v2 branch. Feel free to open another issue for further discussion of ring buffer API.

**Comment by Yepoleb** [comment]
I can see your point now. I've viewed the OS layer as a separate global entity, that's not part of the SoundIo state, which you don't. It's fine to leave it that way.
