### ISSUE TITLE
Compatibility with older ALSA

### ISSUE THREAD

**Issue by capr** [andrewrk/libsoundio#30]
Hi,

Older ALSA (Ubuntu 10) does not have support for channel mapping. Could we have an #ifdef for that? A runtime check would be even better if at all possible.

Thanks.

**Comment by capr** [comment]
Looks like channel mapping API was added in 1.0.27 which was released on [2013-04-12](http://www.alsa-project.org/main/index.php/Changes_v1.0.26_v1.0.27).

**Comment by andrewrk** [comment]
Ubuntu 10 is past its [end of life date](https://wiki.ubuntu.com/Releases), which is April 30, 2015.

**Comment by capr** [comment]
I knew you're going to say that :) Still.. 2013-04 is not very good backwards compat, especially since that probably means 2014 for Debian and other slow distros.

**Comment by andrewrk** [comment]
Let me think about it. I'm reluctant to spend development energy on old stuff, since I could theoretically solve the problem by merely waiting a couple years for people to catch up.

**Comment by andrewrk** [comment]
[Debian Jessie (current stable) has 1.0.28](https://packages.debian.org/source/jessie/alsa-utils)

**Comment by capr** [comment]
I hear ya. It would be helpful to document the compatibility baseline ("requires ALSA 1.0.27+") though. And Debian Jessie was released in April 2015, c'mon. Don't make me go back to PortAudio, please :) Look, I even made a nice Lua binding for it: https://luapower.com/libsoundio which btw you were saying something about code review? ;) It's almost finished - I just need to make binaries for Linux and OSX and I got stuck in this issue.

**Comment by andrewrk** [comment]
What system requirements are you targeting?

**Comment by capr** [comment]
My baseline is OSX 10.7, WinXP and ancient Linuxes (libc 2.7, but realistically Ubuntu 10), 32bit and 64bit. All modules in luapower respect that, so you see why I'd like to keep it that way. I understand your point of view too, especially if your plan is to ship in 2 years. Ah well :)

**Comment by andrewrk** [comment]
libsoundio does not meet your requirements. libsoundio targets:

 * OSX 10.9 or later, although there is currently a bug which only exists for 10.9 and for which there is not yet a known fix.
 * Windows 7 or later
 * Linux with ALSA recent enough to support channel maps, which apparently is 1.0.27.

I'll make this more clear in the documentation.

**Comment by capr** [comment]
Ok, thanks. Unfortunately that means I can't use it right now (but I will in a few years).

**Comment by andrewrk** [comment]
I understand that, and while I do feel sad about that, I only have so much time to spend writing code so I have to try to spend that time optimally.

**Comment by capr** [comment]
Well, if it's any comfort I'll still maintain the luajit binding and keep it as part of luapower just because the libsoundio API was such a pleasure to bind :) I'll just have to find/make another one for people like me who need more market coverage, but I'm sure libsoundio will find it's users too.
