### ISSUE TITLE
OSX not working with sample rates other than the default 44100

### ISSUE THREAD

**Issue by capr** [andrewrk/libsoundio#31]
OSX 10.9 on a MacBook reports 3 sample rate ranges on the default output device (called "Built-in Output"): 44100-44100, 48000-48000 and 96000-96000. I set `stream->sample_rate = 48000` right before opening the stream (I set the format to Float32NE - the only reported format).

If I set the sample rate to anything other than 44100 (including 0), the callback is not called.

What am I missing?

[Unrelated: Windows reports a single sample rate range 8000 - 5644800 but it only works with 44100 and 48000 - 52800 -- should I complain about it in another issue or you had enough of me? :)]

**Comment by andrewrk** [comment]
I believe this is the same issue as #19 which I do want to solve.

As for Windows, yes please file another issue, and be sure to include the windows version and make sure all Windows updates are installed.
