### ISSUE TITLE
unable to open raw ALSA device when latency is 0.35

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/libsoundio#33]
```
$ ./sio_sine --backend alsa --device hw:0,0 --raw  --latency 0.035
Backend: ALSA
Output device: HDA Intel PCH ALC892 Analog
'p\n' - pause
'u\n' - unpause
'c\n' - clear buffer
'q\n' - quit
unable to open device: unable to open device
```

Any other latency works fine. This has got to be an ALSA bug. I sent a message to alsa-devel mailing list.

**Comment by andrewrk** [comment]
I'm interested to see if anyone gets the same behavior on their hardware.

**Comment by diogocp** [comment]
FWIW I get the same weird behavior, and that commit fixes it.
