### ISSUE TITLE
Format differences between portaudio and libsoundio

### ISSUE THREAD

**Issue by roxlu** [andrewrk/libsoundio#34]
Hi Andrew,

Thanks for your great soundio library. I’ve been looking for a good replacement for port audio and libsoundio look really really nice. 

I’m listing the capabilities of a device, but a device for which portaudio tells me to have a 16bit format is not found by libsoundio. How is it possible that there is a difference between formats? 

Thanks
roxlu

**Comment by andrewrk** [comment]
What sound backend are you using in PortAudio and libsoundio?

**Comment by roxlu** [comment]
Hey andrewrk, sorry for the delay but I had to make some changes to get the right info. I was using the default backends for both libraries (soundio/portaudio). Portaudio seems to use CoreAudio by default, so I changed my soundio test code to use the CoreAudio backend. The results are exactly the same.

I've got a function which which lists some of the capabilities of the devices; maybe I'm using libsoundio wrong and isn't this an libsoundio issue.  I've paste my soundio  wrapper here (pointing to the function which checks the capabilities): https://gist.github.com/roxlu/b01aaf884d6119e1a710#file-audiocapturesoundio-cpp-L227 

_Below is the output when I switch backends in my app from portaudio / libsoundio._

PortAudio:
Device: 0, nchannels: 2, samplerate: AUDIO_SAMPLERATE_44100, bitsize: AUDIO_BITSIZE_S16
Device: 0, nchannels: 2, samplerate: AUDIO_SAMPLERATE_44100, bitsize: AUDIO_BITSIZE_F32
Device: 0, nchannels: 2, samplerate: AUDIO_SAMPLERATE_22050, bitsize: AUDIO_BITSIZE_S16
Device: 0, nchannels: 2, samplerate: AUDIO_SAMPLERATE_22050, bitsize: AUDIO_BITSIZE_F32
Device: 0, nchannels: 2, samplerate: AUDIO_SAMPLERATE_11025, bitsize: AUDIO_BITSIZE_S16
Device: 0, nchannels: 2, samplerate: AUDIO_SAMPLERATE_11025, bitsize: AUDIO_BITSIZE_F32

SoundIo
Device: 0, nchannels: 2, samplerate: AUDIO_SAMPLERATE_44100, bitsize: AUDIO_BITSIZE_F32

**Comment by andrewrk** [comment]
What MacOS version are you using? Can you paste the output of sio_list_devices?

**Comment by andrewrk** [comment]
libsoundio does no sample rate conversion, sample format conversion, or channel remapping. It uses the lowest level, lowest latency CoreAudio API, the AUHAL, for which the sample format is always 32-bit floating point little endian, and no AudioUnits are created to do any resampling or anything like that. Based on reading the source code, I believe that PortAudio does initialize an audio pipeline and create an audio unit for sample format conversion.

**Comment by roxlu** [comment]
Ah I see, so it's PortAudio who sets up a pipeline which does the conversion. I guess this issue is solved then.
