### ISSUE TITLE
Use symbol versioning

### ISSUE THREAD

**Issue by fsateler** [andrewrk/libsoundio#40]
If libsoundio is to become a widely used library, it would be great if symbol versioning was provided. Symbol versioning is a more fine grained version of allowing multiple (ABI-incompatible) libraries to coexist in the same system.

Under the current scheme, you have `libsoundio.so.1`. If an ABI-breaking change needed to be made, then `libsoundio.so.2` would be able to exist side by side with `libsoundio.so.1`. However, there is still potential for trouble:

1.  App `foo` is compiled against version 2.
2. `foo` loads a plugin `bar`, which is linked to version 1.
3. Errors occur as the linker somehow determines it needs to use only one version of the library for any given symbol that exists in both libraries, but it can only choose one.

Using a version script tags each function with a trailing string (arbitrary). If a version 2 is released that changes that string, then the runtime linker can use that trailing string to disambiguate between the versions, and so both libraries can coexist in the same process. The version can be inspected via `objdump -T $library`. You can check eg libpulse has all functions tagged with PULSE_0

Symbol versioning can also be used to avoid bumping the version even while making ABI-breaking changes. This is a more advanced usage that is overkill in many cases, but is eg used by glibc (check out `objdump -T /lib/x86_64-linux-gnu/libc.so.6|grep strtod` on a debian system).

The basic usage is fairly simple. All that is needed is that a list of all the exported symbols be listed in a file that then is passed to the linker via the `-Wl,--version-script=$file` flag:

    LIBSOUNDIO_1 {
    global:
        soundio_backend_count;
        soundio_backend_name;
        soundio_best_matching_channel_layout;
        soundio_channel_layout_builtin_count;
        soundio_channel_layout_detect_builtin;
        soundio_channel_layout_equal;
        soundio_channel_layout_find_channel;
        soundio_channel_layout_get_builtin;
        soundio_channel_layout_get_default;
        soundio_connect;
        soundio_connect_backend;
        soundio_create;
        soundio_default_input_device_index;
        soundio_default_output_device_index;
        soundio_destroy;
        soundio_device_equal;
        soundio_device_nearest_sample_rate;
        soundio_device_ref;
        soundio_device_sort_channel_layouts;
        soundio_device_supports_format;
        soundio_device_supports_layout;
        soundio_device_supports_sample_rate;
        soundio_device_unref;
        soundio_disconnect;
        soundio_flush_events;
        soundio_force_device_scan;
        soundio_format_string;
        soundio_get_backend;
        soundio_get_bytes_per_sample;
        soundio_get_channel_name;
        soundio_get_input_device;
        soundio_get_output_device;
        soundio_have_backend;
        soundio_input_device_count;
        soundio_instream_begin_read;
        soundio_instream_create;
        soundio_instream_destroy;
        soundio_instream_end_read;
        soundio_instream_get_latency;
        soundio_instream_open;
        soundio_instream_pause;
        soundio_instream_start;
        soundio_output_device_count;
        soundio_outstream_begin_write;
        soundio_outstream_clear_buffer;
        soundio_outstream_create;
        soundio_outstream_destroy;
        soundio_outstream_end_write;
        soundio_outstream_get_latency;
        soundio_outstream_open;
        soundio_outstream_pause;
        soundio_outstream_start;
        soundio_parse_channel_id;
        soundio_ring_buffer_advance_read_ptr;
        soundio_ring_buffer_advance_write_ptr;
        soundio_ring_buffer_capacity;
        soundio_ring_buffer_clear;
        soundio_ring_buffer_create;
        soundio_ring_buffer_destroy;
        soundio_ring_buffer_fill_count;
        soundio_ring_buffer_free_count;
        soundio_ring_buffer_read_ptr;
        soundio_ring_buffer_write_ptr;
        soundio_sort_channel_layouts;
        soundio_strerror;
        soundio_wait_events;
        soundio_wakeup;
    local: *;
    };

Then, if a change is made that requires bumping SONAME, all you need to do is change the version script to LIBSOUNDIO_2.

More information in the [ld manual](https://sourceware.org/binutils/docs/ld/VERSION.html#VERSION)

**Comment by andrewrk** [comment]
Why does one have to provide a list of function names to get this feature? Why can't ld figure out the list of functions automatically?

**Comment by fsateler** [comment]
You can use `global: *;`, however that only allows the basic usage I outlined (there are more advanced usages described in the manual).
However, that also exports any non-explicitly invisible symbols:

    --- functions.old       2015-10-30 09:26:51.175431958 -0300
    +++ functions.new       2015-10-30 09:26:57.375088105 -0300
    @@ -3,9 +3,6 @@
    soundio_strerror
    soundio_instream_end_read
    soundio_backend_name
    -_ZNKSt13__atomic_baseIlEcvlEv
    -_ZNSt13__atomic_baseIlEaSEl
    -_ZNKSt6atomicIbEcvbEv
    soundio_create
    soundio_default_input_device_index
    soundio_device_supports_format
    @@ -18,7 +15,6 @@
    soundio_ring_buffer_free_count
    soundio_best_matching_channel_layout
    soundio_sort_channel_layouts
    -_ZNSt6atomicIbE5storeEbSt12memory_order
    soundio_device_sort_channel_layouts
    soundio_channel_layout_detect_builtin
    soundio_outstream_create
    @@ -29,7 +25,6 @@
    soundio_instream_get_latency
    soundio_channel_layout_get_default
    soundio_outstream_begin_write
    -_ZNKSt6atomicIbE4loadESt12memory_order
    soundio_get_output_device
    soundio_disconnect
    soundio_parse_channel_id
    @@ -37,9 +32,7 @@
    soundio_get_input_device
    soundio_outstream_get_latency
    soundio_instream_pause
    -_ZNSt6atomicIbEaSEb
    soundio_format_string
    -_ZNSt13__atomic_baseIbEaSEb
    soundio_destroy
    soundio_ring_buffer_advance_write_ptr
    soundio_ring_buffer_write_ptr
    @@ -64,11 +57,9 @@
    soundio_get_channel_name
    soundio_device_nearest_sample_rate
    soundio_ring_buffer_destroy
    -_ZStanSt12memory_orderSt23__memory_order_modifier
    soundio_have_backend
    soundio_outstream_start
    soundio_wait_events
    -_ZNSt13__atomic_baseIlEpLEl
    soundio_force_device_scan
    soundio_outstream_destroy
    soundio_device_equal

**Comment by andrewrk** [comment]
Hmm. I use `-fvisibility=hidden` and then explicitly use compiler attributes to expose functions using `__attribute__((visibility ("default")))` (or equivalent). Shouldn't this be taken into account in this list?

**Comment by fsateler** [comment]
Yes, it is (otherwise you would see more symbol in .text section). However some C++ symbols escape the visibility default. My guess is because they are defined as public in the g++ headers (if you run the missing symbols through c++filt you see they are all std:: symbols), but with implementation in the same header. This results in the instantiated method being publicly visible.

However, I do not care if you use `global: *;` or explicitly list everything. What I do care is that symbol versioning is applied. If this library becomes widely used, then not having symbol versioning will prove painful for migrations.

**Comment by andrewrk** [comment]
I'm not opposed to this, but I don't really understand it yet. Give me some time to play with it and see how it works.

**Comment by andrewrk** [comment]
@fsateler as a first step toward providing symbol versioning, I've converted the source to pure C11. What command were you using to generate the function list?

The code is in the `c11` branch. I still have a couple things to fix before merging that work into master (see #45)

**Comment by andrewrk** [comment]
Update: c11 branch is merged into master now.

**Comment by fsateler** [comment]
You can use `objdump -T libsoundio.so | grep '\.text'` + some awk/sed to
remove the other info (not on my laptop now )

**Comment by andrewrk** [comment]
Well, at least now the list of symbols is automatically correct, without anything escaping.

```
soundio_backend_count
soundio_backend_name
soundio_best_matching_channel_layout
soundio_channel_layout_builtin_count
soundio_channel_layout_detect_builtin
soundio_channel_layout_equal
soundio_channel_layout_find_channel
soundio_channel_layout_get_builtin
soundio_channel_layout_get_default
soundio_connect
soundio_connect_backend
soundio_create
soundio_default_input_device_index
soundio_default_output_device_index
soundio_destroy
soundio_device_equal
soundio_device_nearest_sample_rate
soundio_device_ref
soundio_device_sort_channel_layouts
soundio_device_supports_format
soundio_device_supports_layout
soundio_device_supports_sample_rate
soundio_device_unref
soundio_disconnect
soundio_flush_events
soundio_force_device_scan
soundio_format_string
soundio_get_backend
soundio_get_bytes_per_sample
soundio_get_channel_name
soundio_get_input_device
soundio_get_output_device
soundio_have_backend
soundio_input_device_count
soundio_instream_begin_read
soundio_instream_create
soundio_instream_destroy
soundio_instream_end_read
soundio_instream_get_latency
soundio_instream_open
soundio_instream_pause
soundio_instream_start
soundio_output_device_count
soundio_outstream_begin_write
soundio_outstream_clear_buffer
soundio_outstream_create
soundio_outstream_destroy
soundio_outstream_end_write
soundio_outstream_get_latency
soundio_outstream_pause
soundio_outstream_start
soundio_parse_channel_id
soundio_ring_buffer_advance_read_ptr
soundio_ring_buffer_advance_write_ptr
soundio_ring_buffer_capacity
soundio_ring_buffer_clear
soundio_ring_buffer_create
soundio_ring_buffer_destroy
soundio_ring_buffer_fill_count
soundio_ring_buffer_free_count
soundio_ring_buffer_read_ptr
soundio_ring_buffer_write_ptr
soundio_sort_channel_layouts
soundio_strerror
soundio_wait_events
```

**Comment by andrewrk** [comment]
`--default-symver` is good for the simple case described above.

Unfortunately, symbol versioning is a GNU linker-specific feature, and cmake does not provide a reasonable way to test for linker flag availability, or even to ask what linker is in use. Further, some people [cast doubt](https://blogs.oracle.com/rvs/entry/why_do_i_love_multiple) on whether symbol versioning is even a good idea in general. The fact that `--default-symver` is not on by default is a clue that it's generally not an accepted default.

In libsoundio's specific case, I really don't think symbol versioning is the correct solution to the described problem. An application should only use one version of libsoundio; any more than that is almost certainly poor encapsulation and a gratuitous waste of CPU and memory resources.

I'm going to close this issue. There is too much resistance to adding this, and it's not clear enough to me that this idea is practical and important enough to overcome the resistance.

My mind is open to further discussion or arguments.
