### ISSUE TITLE
Build recommendations for portability on linux

### ISSUE THREAD

**Issue by hotgloupi** [andrewrk/libsoundio#47]
This is not really an issue, but as there is no mention of it in the docs ...

When building against the three available linux backends (alsa, pulseaudio and jack), the binaries have de facto a dependency to these libraries.

I'm about to try to build them statically to avoid package dependencies and/or different builds for every linux distribution flavor. But would you recommend it ?

I could also try to dlopen those, which would have the benefit of using the packaged version, but at the risk of a mismatch of ABIs.

Also, what are you planning to do for your other project Genesis ?

**Comment by andrewrk** [comment]
In general, on Linux it is recommended to use shared libraries. But building statically should work too, and in fact I believe libsoundio provides a static library as well as a shared library by default. 

For Genesis I plan to provide a statically compiled version for Windows and use shared libraries on Linux.

I'm not sure I understand the question - can you explain what is the problem you are trying to solve?

**Comment by fsateler** [comment]
I think the question is "how to ensure libsoundio runs if compiled with pulseaudio but running in a non-pulse system".

Or in other words, how can libsoundio be bundled with an app without (a) imposing install requirements on the target system, (b) also bundling pulse, jack and alsa libraries.

**Comment by andrewrk** [comment]
Ah, I see. libsoundio needs the library code to run, but it detects when the server is not running. For example, if compiled with PulseAudio support, libsoundio depends on libpulse.so (or compiled statically), but when run on a non-pulse system, it will correctly detect that the pulse server is not running and use a different backend. Same thing with JACK.

**Comment by hotgloupi** [comment]
Thanks @fsateler, that was exactly what I meant :)

And thanks @andrewrk for your answers. However I believe there is still a problem if the program is linked dynamically with, let's say pulse audio, the shared library **have** to be there for the program to even run. whereas, when statically linked, it could just check if the server is running.

But if you're planning to build different binaries for every (major) distribution, I assume that won't be a problem (i.e. you can link with pulse audio only if the package for the targeted distribution exists)

Thanks again :)

**Comment by andrewrk** [comment]
My suggestion for deploying on Linux would be to choose one of these options:

1. Provide a package specific to that distribution of linux, such as a .deb on Debian or a PPA for Ubuntu, and use the system dependencies via the package manager.
2. Create a standalone static build with no dependencies that you can run on any linux computer with matching CPU architecture.

What distributions are you targeting? Ideally, libsoundio will already be in the package manager for it and you could rely on that.

**Comment by hotgloupi** [comment]
I'm targeting Windows (>= vista), OS X (>= 10.9) and linux for now. My goal is to have the most uniform and simple build (and deployment) process.

I was asking in the first place because I'm not familiar with how sound libraries and drivers works "on the field".

For example, with opengl (which I use), I can link with the shared library, because I'm pretty sure that the library (libGL.so) is always there, be it a software or a nvidia version of it.
I fact, this simple library is the bridge to speak to the driver, and I can rely on that.

So, if I understand correctly, when it comes to sounds API, we can talk to the driver through multiple implementation (namely alsa, oss, jack, pulse, ...) which are not always provided:
 - The client library might not be installed (libasound.so for example)
 - The server process might not be running (JACK server for example)

While the latter situation is detected by libsoundio, but the former is a problem to me, because I can't force a user to install all backends clients just to run my program.

At this point, there are three options:
   - Build everything statically (and libsoundio will check everything for me)
   - Rely only on the most common backend out there (is it ALSA?)
   - Build libsoundio with all backends (without linking the shared library and allowing undefined symbols) but trying to dlopen the client libraries before using a specific backend.

Thanks again for your time ! 

(Btw, feel free to close this issue at any time, my feelings won't be hurt ;))

**Comment by andrewrk** [comment]
> I can't force a user to install all backends clients just to run my program.

Does your program have any other dependencies? How are you resolving these other dependencies?

**Comment by hotgloupi** [comment]
> Does your program have any other dependencies? How are you resolving these other dependencies?

I bundle every dependency in my package, except OpenGL, libc, and maybe some other reasonable dependencies like libm, libpthread, libstdc++, ... And that's for linux. For OS X, everything that is in /Frameworks should be available (CoreAudio would be one). On windows, I bundle everything except OpenGL.

Regarding ALSA and others, I could bundle them as well, but if you think that I can expect to find libasound.so on every linux desktop, that would be one less thing to worry about :)

In your own projects, do you plan to use the standard package system dependencies ?
Will you have a build for every long support ubuntu (for example) ?
Will you provide build variants that do not require JACK / PulseAudio ?

If that's the case, on what criteria do you choose which platform package will have which dependency ?

I'm following the way of Windows and OS X, I think it's way simpler to use fixed version of every dependency, and bundle them (like skype for example). That's why I'm trying to know which dependency is better left to the OS, like OpenSSL, or maybe ALSA.

**Comment by andrewrk** [comment]
> I bundle every dependency in my package, except OpenGL, libc, and maybe some other reasonable dependencies like libm, libpthread, libstdc++, ... And that's for linux. For OS X, everything that is in /Frameworks should be available (CoreAudio would be one). On windows, I bundle everything except OpenGL.

In this case, on Linux I suggest bundling libsoundio, as well as libasound, libjack, and libpulse. On OS X and Windows, you should only have to bundle libsoundio.

> Regarding ALSA and others, I could bundle them as well, but if you think that I can expect to find libasound.so on every linux desktop, that would be one less thing to worry about :)

You could probably get away with not bundling libasound, but I just checked and it's only 1.3MB. It is possible for a system to not have that installed. If you're already bundling dependencies, might as well throw this one in there.



> In your own projects, do you plan to use the standard package system dependencies ?

For my projects, I plan to get them into the various package managers, for example by uploading the package to Debian: https://packages.debian.org/source/sid/libsoundio

Ubuntu automatically pulls packages from Debian.

Various contributors put libsoundio in other distributions. For example, here's Arch linux: https://aur.archlinux.org/packages/libsoundio/
NixOS: https://github.com/NixOS/nixpkgs/pull/9651

Other than using the package managers, users can install my projects from source using system dependencies. 

> Will you provide build variants that do not require JACK / PulseAudio ?

Either the user will install libsoundio from a package manager, in which case it will depend on libjack and libpulse, or the user will install from source, in which case they can select configure options to enable or disable the jack and pulse backends.



> That's why I'm trying to know which dependency is better left to the OS, like OpenSSL, or maybe ALSA.

I think, for this case, you should be safe bundling the latest stable version of each dependency.

**Comment by hotgloupi** [comment]
Thank you ! I will do that :)

So, to summarize, when targeting an Unix, one must ensure that each selected backend:
 - Has its client libraries statically linked into the program
 - Or that the client libraries installation are enforced by a package dependency
 - Or that the client libraries are shipped along the program

And libsoundio will do the rest :)
