### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by ishmael1851** [andrewrk/libsoundio#51]
Can't compile.  Is there a file missing from the git repo?

libsoundio/src/atomics.h:14:10: fatal error: 'stdatomic.h' file not found

**Comment by ishmael1851** [comment]
This appears to be caused by a known issue with older version of GCC (on Centos 6).

I have:
gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58016

As a workaround, I just downloaded the missing file in my /usr/include directory:
wget https://gist.githubusercontent.com/nhatminhle/5181506/raw/541482dbc61862bba8a156edaae57faa2995d791/stdatomic.h

**Comment by andrewrk** [comment]
I think your solution to this problem is causing #53 .

**Comment by andrewrk** [comment]
libsoundio requires a gcc version new enough that includes the atomics. I believe the minimum number is gcc 4.9.

**Comment by andrewrk** [comment]
Sorry, a recent gcc with stdatomic.h is required to build libsoundio.
