### ISSUE TITLE
unable to compile with old ALSA

### ISSUE THREAD

**Issue by ishmael1851** [andrewrk/libsoundio#52]
libsoundio/src/alsa.h:51:5: error: unknown type name 'snd_pcm_chmap_t'

aplay --version
aplay: version 1.0.23 by Jaroslav Kysela <perex@perex.cz>

**Comment by ishmael1851** [comment]
In order to get the code to compile on Centos 6, I had to install the latest version of ALSA as follows.

sudo -s
yum remove alsa-lib-devel
yum install xmlto

wget http://www.fftw.org/fftw-3.3.4.tar.gz
cd fftw-3.3.4
./configure && make

mkdir -p /usr/src/alsa
cd /usr/src/alsa

wget ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.0.tar.bz2
cd alsa-lib-1.1.0
./configure && make && make install

wget ftp://ftp.alsa-project.org/pub/utils/alsa-utils-1.1.0.tar.bz2
cd ../alsa-utils-1.1.0
./configure && make && make install

cd /usr/lib64/
ln -s ../lib/libasound.so.2.0.0 libasound.so

**Comment by andrewrk** [comment]
Again, sorry, but the requirements are Linux 3.7+ and the version of ALSA that comes with that.
