### ISSUE TITLE
Node bindings?

### ISSUE THREAD

**Issue by dfcreative** [andrewrk/libsoundio#55]
Andrew, hi!

Are there any plans on creating bindings for nodejs?
For now, neither [mpg123](https://www.npmjs.com/package/speaker), [portaudio1](https://www.npmjs.com/package/node-core-audio) nor [portaudio2](https://www.npmjs.com/package/portaudio) work (on windows at least), and no one seems to be willing to do anything about that. The situation is quite sorrowful for those who want to just output sound in nodejs.
If no, can you give any advice on what it is required to get the binding of libsoundio done for node? Skimming the [node-addons](https://nodejs.org/api/addons.html) tutorial gives an outline of how to compile C++ things, but what are the steps to be done to compile libsoundio?

Thank you for any response.

**Comment by andrewrk** [comment]
> Are there any plans on creating bindings for nodejs?

Not as part of this project.



> For now, neither mpg123, portaudio1 nor portaudio2 work (on windows at least), and no one seems to be willing to do anything about that. The situation is quite sorrowful for those who want to just output sound in nodejs.

Outputting sound is typically in the real-time domain of problems, where you'll find more support in compiled languages without a garbage collector.

> If no, can you give any advice on what it is required to get the binding of libsoundio done for node? Skimming the node-addons tutorial gives an outline of how to compile C++ things, but what are the steps to be done to compile libsoundio?

Steps to compile libsoundio can be found in the README.md file.

To make a node addon for libsoundio you would need to introduce more runtime code to deal with the non-realtime nature of javascript.

There are some clues in #28
