### ISSUE TITLE
"out of memory" when compiled with ENABLE_ALSA on kernel with no ALSA support

### ISSUE THREAD

**Issue by diogocp** [andrewrk/libsoundio#6]
My kernel has no sound support. If I compile libsoundio with ALSA support disabled, sio_list_devices shows me the dummy devices. This also works if I compile with PulseAudio support. However, after compiling with ENABLE_ALSA, this happens:

```
# /usr/bin/sio_list_devices
out of memory
```

**Comment by andrewrk** [comment]
Can I get a back trace?

Build in debug mode, then run it like this: 

```
gdb sio_list_devices -ex 'break exit' -ex 'run'
```

**Comment by diogocp** [comment]
I can't seem to get a backtrace, it might be an issue with PaX or grsecurity, but maybe this helps:

    sio_list_devices: /tmp/soundio/libsoundio-1.0.0/src/alsa.cpp:1817: int soundio_alsa_init(SoundIoPrivate*): Assertion `err != 2' failed.

**Comment by andrewrk** [comment]
Alright I believe this is fixed and now on systems for which /dev/snd is missing, the alsa backend will fail and fall back on the dummy backend.

**Comment by diogocp** [comment]
Yes, with 918183a it works correctly. :+1:
