### ISSUE TITLE
Unable compile Raspberry pi 3 

### ISSUE THREAD

**Issue by mjara78** [andrewrk/libsoundio#62]
I can't compile in Raspberry pi 3. I used osmc, a debian base distro.

 Configuring libsoundio version 1.1.0
-- Could NOT find JACK (missing:  JACK_LIBRARY JACK_INCLUDE_DIR)
-- Could NOT find PULSEAUDIO (missing:  PULSEAUDIO_LIBRARY PULSEAUDIO_INCLUDE_DIR)
-- Could NOT find ALSA (missing:  ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Could NOT find COREAUDIO (missing:  COREAUDIO_LIBRARY COREAUDIO_INCLUDE_DIR)
-- Could NOT find WASAPI (missing:  WASAPI_INCLUDE_DIR)

Installation Summary
--------------------
* Install Directory            : /usr/local
* Build Type                   : Debug
* Build static libs            : ON
* Build examples               : ON
* Build tests                  : ON

System Dependencies
-------------------
* threads                      : OK
* JACK       (optional)        : not found
* PulseAudio (optional)        : not found
* ALSA       (optional)        : not found
* CoreAudio  (optional)        : not found
* WASAPI     (optional)        : not found

-- Configuring done
-- Generating done
-- Build files have been written to: /home/osmc/libsoundio/build
osmc@osmc-Ulysses:~/libsoundio/build$
osmc@osmc-Ulysses:~/libsoundio/build$ make
[  3%] Building C object CMakeFiles/libsoundio_shared.dir/src/soundio.c.o
In file included from /home/osmc/libsoundio/src/soundio.c:8:0:
/home/osmc/libsoundio/src/soundio_private.h:112:49: error: unknown type name 'SoundIoListDevicePtr'
 SOUNDIO_MAKE_LIST_STRUCT(struct SoundIoDevice*, SoundIoListDevicePtr, SOUNDIO_LIST_NOT_STATIC)
                                                 ^
/home/osmc/libsoundio/src/soundio_private.h:112:71: error: unknown type name 'SOUNDIO_LIST_NOT_STATIC'
 SOUNDIO_MAKE_LIST_STRUCT(struct SoundIoDevice*, SoundIoListDevicePtr, SOUNDIO_LIST_NOT_STATIC)
    ^
/home/osmc/libsoundio/src/soundio_private.h:121:2: error: ISO C does not allow extra ';' outside of a function [-Werror=pedantic]
 };
  ^
/home/osmc/libsoundio/src/soundio_private.h:168:57: error: unknown type name 'SoundIoListSampleRateRange'
 SOUNDIO_MAKE_LIST_STRUCT(struct SoundIoSampleRateRange, SoundIoListSampleRateRange, SOUNDIO_LIST_NOT_STATIC)
                                                         ^
/home/osmc/libsoundio/src/soundio_private.h:168:85: error: unknown type name 'SOUNDIO_LIST_NOT_STATIC'
 SOUNDIO_MAKE_LIST_STRUCT(struct SoundIoSampleRateRange, SoundIoListSampleRateRange, SOUNDIO_LIST_NOT_STATIC)
                  ^
/home/osmc/libsoundio/src/soundio_private.h:178:2: error: ISO C does not allow extra ';' outside of a function [-Werror=pedantic]
 };
  ^
/home/osmc/libsoundio/src/soundio.c:73:46: error: unknown type name 'SoundIoListDevicePtr'
 SOUNDIO_MAKE_LIST_DEF(struct SoundIoDevice*, SoundIoListDevicePtr, SOUNDIO_LIST_NOT_STATIC)
                                              ^
/home/osmc/libsoundio/src/soundio.c:73:68: error: unknown type name 'SOUNDIO_LIST_NOT_STATIC'
 SOUNDIO_MAKE_LIST_DEF(struct SoundIoDevice*, SoundIoListDevicePtr, SOUNDIO_LIST_NOT_STATIC)
 ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_input_device_count':
/home/osmc/libsoundio/src/soundio.c:302:33: error: dereferencing pointer to incomplete type
     return si->safe_devices_info->input_devices.length;
                                 ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_output_device_count':
/home/osmc/libsoundio/src/soundio.c:316:33: error: dereferencing pointer to incomplete type
     return si->safe_devices_info->output_devices.length;
                                 ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_default_input_device_index':
/home/osmc/libsoundio/src/soundio.c:330:33: error: dereferencing pointer to incomplete type
     return si->safe_devices_info->default_input_index;
                                 ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_default_output_device_index':
/home/osmc/libsoundio/src/soundio.c:344:33: error: dereferencing pointer to incomplete type
     return si->safe_devices_info->default_output_index;
                                 ^
In file included from /home/osmc/libsoundio/src/soundio.c:14:0:
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_get_input_device':
/home/osmc/libsoundio/src/soundio.c:359:41: error: dereferencing pointer to incomplete type
     assert(index < si->safe_devices_info->input_devices.length);
                                         ^
/home/osmc/libsoundio/src/soundio.c:360:52: error: dereferencing pointer to incomplete type
     if (index < 0 || index >= si->safe_devices_info->input_devices.length)
                                                    ^
/home/osmc/libsoundio/src/soundio.c:363:12: error: implicit declaration of function 'SoundIoListDevicePtr_val_at' [-Werror=implicit-function-declaration]
     struct SoundIoDevice *device = SoundIoListDevicePtr_val_at(&si->safe_devices_info->input_devices, index);
            ^
/home/osmc/libsoundio/src/soundio.c:363:86: error: dereferencing pointer to incomplete type
     struct SoundIoDevice *device = SoundIoListDevicePtr_val_at(&si->safe_devices_info->input_devices, index);
                   ^
In file included from /home/osmc/libsoundio/src/soundio.c:14:0:
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_get_output_device':
/home/osmc/libsoundio/src/soundio.c:380:41: error: dereferencing pointer to incomplete type
     assert(index < si->safe_devices_info->output_devices.length);
                                         ^
/home/osmc/libsoundio/src/soundio.c:381:52: error: dereferencing pointer to incomplete type
     if (index < 0 || index >= si->safe_devices_info->output_devices.length)
                                                    ^
/home/osmc/libsoundio/src/soundio.c:384:86: error: dereferencing pointer to incomplete type
     struct SoundIoDevice *device = SoundIoListDevicePtr_val_at(&si->safe_devices_info->output_devices, index);
                   ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_device_unref':
/home/osmc/libsoundio/src/soundio.c:398:16: error: dereferencing pointer to incomplete type
         if (dev->destruct)
                ^
/home/osmc/libsoundio/src/soundio.c:399:16: error: dereferencing pointer to incomplete type
             dev->destruct(dev);
                ^
/home/osmc/libsoundio/src/soundio.c:404:41: error: dereferencing pointer to incomplete type
         if (device->sample_rates != &dev->prealloc_sample_rate_range &&
                                         ^
/home/osmc/libsoundio/src/soundio.c:405:40: error: dereferencing pointer to incomplete type
             device->sample_rates != dev->sample_rates.items)
                                        ^
/home/osmc/libsoundio/src/soundio.c:409:9: error: implicit declaration of function 'SoundIoListSampleRateRange_deinit' [-Werror=implicit-function-declaration]
         SoundIoListSampleRateRange_deinit(&dev->sample_rates);
         ^
/home/osmc/libsoundio/src/soundio.c:409:47: error: dereferencing pointer to incomplete type
         SoundIoListSampleRateRange_deinit(&dev->sample_rates);
                                               ^
/home/osmc/libsoundio/src/soundio.c:411:36: error: dereferencing pointer to incomplete type
         if (device->formats != &dev->prealloc_format)
                                    ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_destroy_devices_info':
/home/osmc/libsoundio/src/soundio.c:679:37: error: dereferencing pointer to incomplete type
     for (int i = 0; i < devices_info->input_devices.length; i += 1)
                                     ^
/home/osmc/libsoundio/src/soundio.c:680:71: error: dereferencing pointer to incomplete type
         soundio_device_unref(SoundIoListDevicePtr_val_at(&devices_info->input_devices, i));
    ^
/home/osmc/libsoundio/src/soundio.c:681:37: error: dereferencing pointer to incomplete type
     for (int i = 0; i < devices_info->output_devices.length; i += 1)
                                     ^
/home/osmc/libsoundio/src/soundio.c:682:71: error: dereferencing pointer to incomplete type
         soundio_device_unref(SoundIoListDevicePtr_val_at(&devices_info->output_devices, i));
    ^
/home/osmc/libsoundio/src/soundio.c:684:5: error: implicit declaration of function 'SoundIoListDevicePtr_deinit' [-Werror=implicit-function-declaration]
     SoundIoListDevicePtr_deinit(&devices_info->input_devices);
     ^
/home/osmc/libsoundio/src/soundio.c:684:46: error: dereferencing pointer to incomplete type
     SoundIoListDevicePtr_deinit(&devices_info->input_devices);
                                              ^
/home/osmc/libsoundio/src/soundio.c:685:46: error: dereferencing pointer to incomplete type
     SoundIoListDevicePtr_deinit(&devices_info->output_devices);
                                              ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_input_device_count':
/home/osmc/libsoundio/src/soundio.c:303:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_output_device_count':
/home/osmc/libsoundio/src/soundio.c:317:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_default_input_device_index':
/home/osmc/libsoundio/src/soundio.c:331:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
/home/osmc/libsoundio/src/soundio.c: In function 'soundio_default_output_device_index':
/home/osmc/libsoundio/src/soundio.c:345:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
CMakeFiles/libsoundio_shared.dir/build.make:54: recipe for target 'CMakeFiles/libsoundio_shared.dir/src/soundio.c.o' failed
make[2]: *** [CMakeFiles/libsoundio_shared.dir/src/soundio.c.o] Error 1
CMakeFiles/Makefile2:192: recipe for target 'CMakeFiles/libsoundio_shared.dir/all' failed
make[1]: *** [CMakeFiles/libsoundio_shared.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Please, need some help.

**Comment by andrewrk** [comment]
> -- Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR)
> -- Could NOT find PULSEAUDIO (missing: PULSEAUDIO_LIBRARY PULSEAUDIO_INCLUDE_DIR)
> -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)

You need to install the appropriate packages before configuring libsoundio. On Debian, it's these:

* libjack-jackd2-dev
* libpulse-dev
* libasound2-dev


As for the other errors, what compiler version are you using?

**Comment by mjara78** [comment]
Thanks.
I wanted to install libsoundio because it is a dependency of libgroove. I want to install groove basin.

I tried installing version 1.0.3 and compile without errors. But libgroove has compiled with errors.

 ```
dpkg --list | grep compiler
 ii  g++                                  4:4.9.2-2                            armhf        GNU C++ compiler
 ii  g++-4.9                              4.9.2-10                             armhf        GNU C++ compiler
 ii  gcc                                  4:4.9.2-2                            armhf        GNU C compiler
 ii  gcc-4.9                              4.9.2-10                             armhf        GNU C compiler
 ii  libxkbcommon0:armhf                  0.4.3-2                              armhf        library interface to the XKB compiler - shared library
```
I try to install these packages and reinstall with version 1.1.0.

**Comment by andrewrk** [comment]
If your goal is to install groove basin then I suggest installing the latest release of libgroove, not master branch. Latest release does not depend on libsoundio and I am still working out the kinks in libgroove master before making a release.

**Comment by mjara78** [comment]
Where can found the latest release of libgroove?

**Comment by andrewrk** [comment]
It might be in your Debian repository already. Try apt-cache search groove.

**Comment by mjara78** [comment]
Thanks

**Comment by klingtnet** [comment]
I can confirm that it can be successfully compiled, at least against ALSA, on a raspberry pi 3 running raspian.

**Comment by andrewrk** [comment]
Thanks @klingtnet
