### ISSUE TITLE
SDL2, JUCE comparisons could use updates in wiki, website

### ISSUE THREAD

**Issue by MrMormon** [andrewrk/libsoundio#68]
The wiki was last updated September 2015 (and the website relies on it).
[SDL2 supports PulseAudio now.](http://wiki.libsdl.org/FAQUsingSDL)
[JUCE](https://www.juce.com/) 4.0 (now 4.2) was released in November.

**Comment by andrewrk** [comment]
I don't see a "yes" in the 2.0 box for SDL. Also feel free to edit the wiki page, it's a wiki on purpose!

**Comment by MrMormon** [comment]
The are two pulseaudio rows there, so a quick glance can miss it. Besides my laziness, the top half of each wiki page requires knowledge of how libsoundio and the alternative are written.

So if it's all right to leave this open, an issue at least points to future work to keep the pros/cons honest. :)

**Comment by andrewrk** [comment]
I just read the release notes from JUCE 4.0, 4.1, 4.2 and looks like there is nothing to report. If you or anyone else notices any inaccuracies in the wiki pages, by all means please update them.
