### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by 7890** [andrewrk/libsoundio#7]
Hi,
trying to compile libsoundio i get this error:
```
..
System Dependencies
-------------------
* threads                      : OK
* JACK       (optional)        : OK
* PulseAudio (optional)        : OK
* ALSA       (optional)        : OK
* CoreAudio  (optional)        : not found
* WASAPI     (optional)        : not found

..
[  2%] Building CXX object CMakeFiles/libsoundio_shared.dir/src/jack.cpp.o
/libsoundio/src/jack.cpp: In function ‘int soundio_jack_init(SoundIoPrivate*)’:
/mnt/data/gb1/home/srv/source/git/libsoundio/src/jack.cpp:919:84: error: invalid conversion from ‘void (*)(jack_port_id_t, const char*, const char*, void*) {aka void (*)(unsigned int, const char*, const char*, void*)}’ to ‘JackPortRenameCallback {aka int (*)(unsigned int, const char*, const char*, void*)}’ [-fpermissive]
     if ((err = jack_set_port_rename_callback(sij->client, port_rename_calllback, si))) {
                                                                                    ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-c99-extensions" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/libsoundio_shared.dir/src/jack.cpp.o] Error 1
make[1]: *** [CMakeFiles/libsoundio_shared.dir/all] Error 2
make: *** [all] Error 2
```
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
How could this be resolved?
Thanks
Thomas

**Comment by diogocp** [comment]
What version of jack do you have installed? I think that is because it requires jack2.

**Comment by andrewrk** [comment]
This is due to a bug in jack2 which was fixed here: https://github.com/jackaudio/jack2/commit/05216197b491d64036733a2d3be511456c1f65cd

**Comment by 7890** [comment]
$ jackd --version
jackdmp 1.9.11
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp version 1.9.11 tmpdir /dev/shm protocol 8

**Comment by andrewrk** [comment]
The problem is that the old version of jack2 that you have does not meet the official jack API specification. So your choices are either: update your jack2 to include this fix, or compile libsoundio without jack support.

**Comment by diogocp** [comment]
@andrewrk is jack1 supported? I tried with 0.121.3 and it failed.

**Comment by 7890** [comment]
updating jack2 helped. thanks!

**Comment by andrewrk** [comment]
@diogocp I've never tested with jack1, but it should theoretically work. I'm willing to take a look at a problem if you file an issue.

**Comment by 7890** [comment]
```
$ ./unit_tests 
testing os_get_time...OK
testing create output stream...OK
testing ring buffer basic...OK
testing ring buffer threaded...OK
```

interesting to know (about jack2) and also thanks to falktx for the fix!
cheers

**Comment by jasonMisaq** [comment]
@andrewrk which file in the source tree should I edit to make it work with jack1? I have jack 1.9.10
