### ISSUE TITLE
Starting an input stream results in very high CPU usage

### ISSUE THREAD

**Issue by jacquesh** [andrewrk/libsoundio#73]
When using the 1.1.0 release dll on Windows (7, 64-bit), libsoundio maxes out a CPU when I start an input stream. A minimal example to reproduce it is below. It sleeps for 10 seconds so you can see that it is actually libsoundio thats causing the CPU usage (I use ProcessExplorer which breaks down usage per thread, see the image below)

![libsoundiocpu](https://cloud.githubusercontent.com/assets/4639662/14885904/51893e44-0d4e-11e6-8874-65328b564d56.png)
```
#include <windows.h>
#include "soundio.h"

void readCallback(SoundIoInStream* stream, int frameCountMin, int frameCountMax)
{
    SoundIoChannelArea* inArea;
    soundio_instream_begin_read(stream, &inArea, &frameCountMax);
    soundio_instream_end_read(stream);
}

int main(int argc, char** argv)
{
    SoundIo* soundio = soundio_create();
    soundio_connect(soundio);
    soundio_flush_events(soundio);

    int defaultDevice = soundio_default_input_device_index(soundio);
    SoundIoDevice* device = soundio_get_input_device(soundio, defaultDevice);
    SoundIoInStream* stream = soundio_instream_create(device);
    stream->read_callback = readCallback;
    stream->sample_rate = 48000;
    stream->format = SoundIoFormatFloat32NE;

    soundio_instream_open(stream);
    soundio_instream_start(stream);

    Sleep(10000);
}
```

**Comment by jacquesh** [comment]
Having read the docs more clearly while looking into a different issue, I see the lower software_latency corresponds to greater CPU usage. The input device defaulted to 0.0s latency and setting it to 0.01s or 0.005s solves the issue.
The docs say that software_latency "Defaults to a large value, potentially upwards of 2 seconds." so either that is no longer true or this is still a bug (as opposed to just my having not read the docs properly)

**Comment by andrewrk** [comment]
Thanks for the error report. I pushed a commit to master branch which I think should solve this. Are you able to build from source to give it a try?

Perhaps I could look into wrapping up #49 if you're using MSVC.

**Comment by jacquesh** [comment]
I am using MSVC, but I'll see if I can get a comparison on a linux machine if that happens before you manage to fix MSVC-building

**Comment by jacquesh** [comment]
I can confirm that it's fixed now.

**Comment by andrewrk** [comment]
Thanks!
