### ISSUE TITLE
WASAPI disconnects if it encounters an error while collecting device information

### ISSUE THREAD

**Issue by jacquesh** [andrewrk/libsoundio#80]
Any error encountered while gathering available device information during WASAPI's search for devices (such as when it first connects) causes the backend to immediately disconnect.
For example if a single device is open in exclusive mode, the entire backend will disconnect immediately.

I can get a fix for this done sometime soon (hopefully). I would assume that the correct response is to set probe_error (or something to that effect) and continue with the other devices, is this correct?
I'll just need to figure out what cleanup needs to be done (if any?) for each device.

**Comment by andrewrk** [comment]
> I would assume that the correct response is to set probe_error (or something to that effect) and continue with the other devices, is this correct?

That is correct.

There are still circumstances when disconnecting the backend is appropriate, however. For example, if `IMMDeviceCollection_GetCount` returns an error, we were unable to even figure out how many devices there are, that's an unexpected unrecoverable error that does not apply to a single device, so the appropriate behavior in this circumstance is to disconnect the backend.

**Comment by andrewrk** [comment]
I think the reason this problem exist is that when I coded this up the first time, it looked to me like an exclusive device would not prevent a probe, but it looks like I was mistaken.

**Comment by jacquesh** [comment]
Well it seems that you were in fact, not mistaken. I tried running the sio_sine test, opening the output device in raw mode and when I ran another instance of it and it responded correctly, WASAPI connected and it just failed to open the device. So it would seem that my particular error isn't caused (solely) by another device being open in exclusive mode, there must be something else making it fail.

I think the issue is still valid though...failing to get a device's friendly name (for example) should probably not kill the entire backend.

**Comment by andrewrk** [comment]
I agree that if there is an error with a specific device only, we can set `probe_error` on that device and continue probing the rest of the devices.

**Comment by andrewrk** [comment]
You probably don't have the code lying around anymore, but one thing that would be really helpful is if you put a breakpoint on your backend disconnected callback function. Then when it unexpectedly was called we could look at the backtrace and discover where exactly in libsoundio it was disconnecting the backend.

**Comment by jacquesh** [comment]
Sorry for the super-delayed response, I've had this on my list of "things to get to sometime" for ages.
I've forgotten exactly what it was but I did have data on exactly what was causing the disconnect and just never got round to putting together a reasonable patch that handled it differently.

I'll try get round to getting more specific details or an actual fix soon but from a quick scan over the source code I'm pretty sure it's disconnecting in the first refresh_devices that runs when it connects to the backend.

**Comment by jacquesh** [comment]
Ok so I got to run it on the PC that was giving me trouble in the past, it seems to work now for some reason. It isn't my pc (it's a friends) but to the best of my knowledge there isn't anything that's changed that I would expect to fix the problem so I can't do very much reasoning about it unfortunately.

As far as I can remember, I *think* it was [this line](https://github.com/andrewrk/libsoundio/blob/8583897d721dd301d4f1b8bf1396a9c8b2a426a8/src/wasapi.c#L905) but the error that caused the disconnect was definitely AUDCLNT_E_DEVICE_IN_USE.

But for example as far as I can tell the handful of error returns that follow that line could all just flag the device with probe_error and continue with other devices.
