### ISSUE TITLE
example/sio_sine.c doesn't unref devices

### ISSUE THREAD

**Issue by 0joshuaolson1** [andrewrk/libsoundio#82]
Unlike [sio_list_devices.c](https://github.com/andrewrk/libsoundio/blob/master/example/sio_list_devices.c), [sio_microphone.c](https://github.com/andrewrk/libsoundio/blob/master/example/sio_microphone.c), and [sio_record.c](https://github.com/andrewrk/libsoundio/blob/master/example/sio_record.c), [sio_sine.c](https://github.com/andrewrk/libsoundio/blob/master/example/sio_sine.c) doesn't unref unused devices when looping through them. Is this intentional?

**Comment by andrewrk** [comment]
> Is this intentional?

No. You found a bug in the example.
