### ISSUE TITLE
'enum' in some places, 'int' in others

### ISSUE THREAD

**Issue by 0joshuaolson1** [andrewrk/libsoundio#83]
I'm not very familiar with C, but I'm looking through [soundio.c](https://github.com/andrewrk/libsoundio/blob/master/src/soundio.c) and [soundio.h](https://github.com/andrewrk/libsoundio/blob/master/soundio/soundio.h) to patch in some functions for a programming language that can't access struct fields/members behind pointers. To me, `enum` versus `int` usage looks haphazard outside of actual enum definitions. For example, `SoundIoError`'s are `int` but `SoundIoBackend`'s and `SoundIoFormat`'s are `enum`.

**Comment by andrewrk** [comment]
I'm having trouble understanding the problem here. Can you elaborate?

**Comment by 0joshuaolson1** [comment]
This looks like inconsistent style, so I was wondering if there was a good reason. At first I thought I had to handle enums and ints differently.

**Comment by andrewrk** [comment]
Enum is used when it makes sense to switch on the value. This is not true for errors but it is true for SoundIOBackend and SoundIoFormat.

**Comment by 0joshuaolson1** [comment]
Great, thank you.
