### ISSUE TITLE
missing soundio_device_unref in example

### ISSUE THREAD

**Issue by trad-emark** [andrewrk/libsoundio#88]
In file example/sio_sine.c near line 185 is missing a call to soundio_device_unref.

**Comment by andrewrk** [comment]
I believe you're looking at an older version, as this was reported in #82 and fixed in 67746c42eca519ed8a3a657de028e47a659629a0.

**Comment by andrewrk** [comment]
Comment if this is not the case, and I'll re-open.

**Comment by trad-emark** [comment]
You are right. I noticed it in 1.1.0 downloaded file and forgot to compare it with master. I apologize for the inconvenience.

**Comment by andrewrk** [comment]
No worries.
