### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by paked** [andrewrk/libsoundio#97]
Your website is currently offline. Not sure if this is intentional, maybe it's discontinued? Anyway, this is what I see - Looks like you just need to repurchase the domain.

![selection_001](https://cloud.githubusercontent.com/assets/8407370/17474761/078342e8-5d9b-11e6-890a-66162bc9bfc3.png)

**Comment by andrewrk** [comment]
Oh no! Thank you for telling me.

**Comment by andrewrk** [comment]
I'm working with the person who currently owns the domain to transfer it to me so that I can renew it.

**Comment by andrewrk** [comment]
Alright we're back up now. I'm sorry about the downtime. The domain is now in my own account and set to auto-renew. Thanks again for the report.
